### ISSUE TITLE
Baileys WS Connection Error - Cannot generate QR Code

### ISSUE THREAD

**Issue by AlejoTorres2001** [EvolutionAPI/evolution-api#1014]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

I have a fresh install for Evolution API V2 usign the following Stack:
On a Azure VM I have installed Portainer Along with Caddy as a reverse proxy, then created a postgres instance a Redis instances, a RabbitMQ  instance and finally the EvoApiV2 instance.

The Api instance is working correctly, I can reach it through the designated subdomain and also access the manager and create instances. (Message queue + redis cache + database are working as expected).
The problem comes when trying to generate a QR code to link instances using Baileys. The QRcode never loads. I have activated baileys logs in my evoApi instance. and the following emerges each time I want to generate the code  (lee log section)

### What did you expect?

QrCode Being exposed by the Manager to be able to link devices to instances.

### What did you observe instead of what you expected?

The QRcode never loads. Refering errors about the connection been refused, causing exceptions in Baileys library

### Which version of the API are you using?

atendai/evolution-api:latest  also tried with atendai/evolution-api:v2.2.0

### What is your environment?

Linux

### Other environment specifications

Azure VM: 4vcpu 16gb RAM

### If applicable, paste the log output

`2024/10/30 09:39AM 30 pid=184 hostname=0936139aee1b node={"passive":false,"userAgent":{"platform":"WEB","appVersion":{"primary":2,"secondary":2413,"tertiary":51},"osVersion":"0.1","device":"Desktop","osBuildNumber":"0.1","releaseChannel":"RELEASE","localeLanguageIso6391":"en","localeCountryIso31661Alpha2":"US"},"webInfo":{"webSubPlatform":"WEB_BROWSER"},"connectType":"WIFI_UNKNOWN","connectReason":"USER_ACTIVATED","devicePairingData":{"eRegid":"AAAAUg==","eKeytype":"BQ==","eIdent":"mdUQDirxAaD25lJCvT0YLHxa6G8yYuuhiZlr0GiLOHI=","eSkeyId":"AAAB","eSkeyVal":"E9Z1YuatNmqKB6E3duf5r/WzFOEILjxUxRwpdsI6LAc=","eSkeySig":"oyqKXvhNs8wd7gPsvbAOyyBJlqY9LRJE8t1w+OEGHTnoXMIxNEZ9EsyRlV1VzB7zbWdF7vOrSu/rgf/NTdE/hQ==","buildHash":"NQC8AaPs3J4zKlANa8yy3g==","deviceProps":"CgdFbXBhdGlhGAEgAA=="}} msg=not logged in, attempting registration...

2024/10/30 09:39AM 30 pid=184 hostname=0936139aee1b trace=Error: Connection Failure
    at WebSocketClient.<anonymous> (/evolution/node_modules/baileys/lib/Socket/socket.js:524:13)
    at WebSocketClient.emit (node:events:519:28)
    at /evolution/node_modules/baileys/lib/Socket/socket.js:236:35
    at Object.decodeFrame (/evolution/node_modules/baileys/lib/Utils/noise-handler.js:144:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) msg=connection errored

2024/10/30 09:39AM 30 pid=184 hostname=0936139aee1b browser=["Empatia","Chrome","6.8.0-1016-azure"] helloMsg={"clientHello":{"ephemeral":"wPsPAa5aVt5Zkbo3CMaO9m34YJiHXVFSoy6f9lbqWEE="}} msg=connected to WA

2024/10/30 09:39AM 30 pid=184 hostname=0936139aee1b node={"passive":false,"userAgent":{"platform":"WEB","appVersion":{"primary":2,"secondary":2413,"tertiary":51},"osVersion":"0.1","device":"Desktop","osBuildNumber":"0.1","releaseChannel":"RELEASE","localeLanguageIso6391":"en","localeCountryIso31661Alpha2":"US"},"webInfo":{"webSubPlatform":"WEB_BROWSER"},"connectType":"WIFI_UNKNOWN","connectReason":"USER_ACTIVATED","devicePairingData":{"eRegid":"AAAAng==","eKeytype":"BQ==","eIdent":"wwvbZUOD2x6NLWJ1P2V9ZQDi4mf4b/C/WcuF0g7Bygc=","eSkeyId":"AAAB","eSkeyVal":"czC6P6R08TeCdcsC8Wd1DQLDXj0Jaa5b8+kFMZdZBxk=","eSkeySig":"+8CewC+F5TEzJmRUXcfuESbsu2L9SJKcz3NWDsT5sEXDuBXnhkkQKuqh5R2U3ffX0otbf/Rq7rxXEijFNLebig==","buildHash":"NQC8AaPs3J4zKlANa8yy3g==","deviceProps":"CgdFbXBhdGlhGAEgAA=="}} msg=not logged in, attempting registration...

2024/10/30 09:39AM 30 pid=184 hostname=0936139aee1b trace=Error: Connection Failure
    at WebSocketClient.<anonymous> (/evolution/node_modules/baileys/lib/Socket/socket.js:524:13)
    at WebSocketClient.emit (node:events:519:28)
    at /evolution/node_modules/baileys/lib/Socket/socket.js:236:35
    at Object.decodeFrame (/evolution/node_modules/baileys/lib/Utils/noise-handler.js:144:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) msg=connection errored

2024/10/30 09:39AM 30 pid=184 hostname=0936139aee1b browser=["Empatia","Chrome","6.8.0-1016-azure"] helloMsg={"clientHello":{"ephemeral":"oGMLPxNqEJVMyCg10odavCkAvx/9K8OEW3pO/lLKBlk="}} msg=connected to WA

2024/10/30 09:39AM 30 pid=184 hostname=0936139aee1b node={"passive":false,"userAgent":{"platform":"WEB","appVersion":{"primary":2,"secondary":2413,"tertiary":51},"osVersion":"0.1","device":"Desktop","osBuildNumber":"0.1","releaseChannel":"RELEASE","localeLanguageIso6391":"en","localeCountryIso31661Alpha2":"US"},"webInfo":{"webSubPlatform":"WEB_BROWSER"},"connectType":"WIFI_UNKNOWN","connectReason":"USER_ACTIVATED","devicePairingData":{"eRegid":"AAAAUg==","eKeytype":"BQ==","eIdent":"mdUQDirxAaD25lJCvT0YLHxa6G8yYuuhiZlr0GiLOHI=","eSkeyId":"AAAB","eSkeyVal":"E9Z1YuatNmqKB6E3duf5r/WzFOEILjxUxRwpdsI6LAc=","eSkeySig":"oyqKXvhNs8wd7gPsvbAOyyBJlqY9LRJE8t1w+OEGHTnoXMIxNEZ9EsyRlV1VzB7zbWdF7vOrSu/rgf/NTdE/hQ==","buildHash":"NQC8AaPs3J4zKlANa8yy3g==","deviceProps":"CgdFbXBhdGlhGAEgAA=="}} msg=not logged in, attempting registration...

2024/10/30 09:39AM 30 pid=184 hostname=0936139aee1b trace=Error: Connection Failure
    at WebSocketClient.<anonymous> (/evolution/node_modules/baileys/lib/Socket/socket.js:524:13)
    at WebSocketClient.emit (node:events:519:28)
    at /evolution/node_modules/baileys/lib/Socket/socket.js:236:35
    at Object.decodeFrame (/evolution/node_modules/baileys/lib/Utils/noise-handler.js:144:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) msg=connection errored

2024/10/30 09:39AM 30 pid=184 hostname=0936139aee1b trace=Error: Connection Failure
    at WebSocketClient.<anonymous> (/evolution/node_modules/baileys/lib/Socket/socket.js:524:13)
    at WebSocketClient.emit (node:events:519:28)
    at /evolution/node_modules/baileys/lib/Socket/socket.js:236:35
    at Object.decodeFrame (/evolution/node_modules/baileys/lib/Utils/noise-handler.js:144:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) msg=connection errored

2024/10/30 09:39AM 30 pid=184 hostname=0936139aee1b browser=["Empatia","Chrome","6.8.0-1016-azure"] helloMsg={"clientHello":{"ephemeral":"qIeW0XAXgvXGFYR78ounRfZ1FSA6U9soMUyX5rAyFkk="}} msg=connected to WA

2024/10/30 09:39AM 30 pid=184 hostname=0936139aee1b node={"passive":false,"userAgent":{"platform":"WEB","appVersion":{"primary":2,"secondary":2413,"tertiary":51},"osVersion":"0.1","device":"Desktop","osBuildNumber":"0.1","releaseChannel":"RELEASE","localeLanguageIso6391":"en","localeCountryIso31661Alpha2":"US"},"webInfo":{"webSubPlatform":"WEB_BROWSER"},"connectType":"WIFI_UNKNOWN","connectReason":"USER_ACTIVATED","devicePairingData":{"eRegid":"AAAAng==","eKeytype":"BQ==","eIdent":"wwvbZUOD2x6NLWJ1P2V9ZQDi4mf4b/C/WcuF0g7Bygc=","eSkeyId":"AAAB","eSkeyVal":"czC6P6R08TeCdcsC8Wd1DQLDXj0Jaa5b8+kFMZdZBxk=","eSkeySig":"+8CewC+F5TEzJmRUXcfuESbsu2L9SJKcz3NWDsT5sEXDuBXnhkkQKuqh5R2U3ffX0otbf/Rq7rxXEijFNLebig==","buildHash":"NQC8AaPs3J4zKlANa8yy3g==","deviceProps":"CgdFbXBhdGlhGAEgAA=="}} msg=not logged in, attempting registration...

2024/10/30 09:39AM 30 pid=184 hostname=0936139aee1b browser=["Empatia","Chrome","6.8.0-1016-azure"] helloMsg={"clientHello":{"ephemeral":"GzNStk3EPYaVVZSLqMOmsSUFjkEpjLdKZRMJh7rTxR8="}} msg=connected to WA

2024/10/30 09:39AM 30 pid=184 hostname=0936139aee1b node={"passive":false,"userAgent":{"platform":"WEB","appVersion":{"primary":2,"secondary":2413,"tertiary":51},"osVersion":"0.1","device":"Desktop","osBuildNumber":"0.1","releaseChannel":"RELEASE","localeLanguageIso6391":"en","localeCountryIso31661Alpha2":"US"},"webInfo":{"webSubPlatform":"WEB_BROWSER"},"connectType":"WIFI_UNKNOWN","connectReason":"USER_ACTIVATED","devicePairingData":{"eRegid":"AAAAUg==","eKeytype":"BQ==","eIdent":"mdUQDirxAaD25lJCvT0YLHxa6G8yYuuhiZlr0GiLOHI=","eSkeyId":"AAAB","eSkeyVal":"E9Z1YuatNmqKB6E3duf5r/WzFOEILjxUxRwpdsI6LAc=","eSkeySig":"oyqKXvhNs8wd7gPsvbAOyyBJlqY9LRJE8t1w+OEGHTnoXMIxNEZ9EsyRlV1VzB7zbWdF7vOrSu/rgf/NTdE/hQ==","buildHash":"NQC8AaPs3J4zKlANa8yy3g==","deviceProps":"CgdFbXBhdGlhGAEgAA=="}} msg=not logged in, attempting registration...

2024/10/30 09:39AM 30 pid=184 hostname=0936139aee1b trace=Error: Connection Failure
    at WebSocketClient.<anonymous> (/evolution/node_modules/baileys/lib/Socket/socket.js:524:13)
    at WebSocketClient.emit (node:events:519:28)
    at /evolution/node_modules/baileys/lib/Socket/socket.js:236:35
    at Object.decodeFrame (/evolution/node_modules/baileys/lib/Utils/noise-handler.js:144:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) msg=connection errored`

### Additional Notes

UPDATES: I have done a fresh install following this well-detailed guide on how to deploy Portainer alongside Traefik in a VM. https://www.youtube.com/watch?v=AHiY_oiJrHw&ab_channel=CursoDev. Using Portainer I have successfully deployed Postgres, Redis, and an Instance of EvolutionAPIV2 [2.1.0]. The problem comes when creating a new instance and generating a new QR code to link my device to it. It never gets generated. Looking at the logs I have noticed that the Baileys service is stuck in a loop, trying to initialize When I click to generate a new QR code. "[Evolution API]  [test]  v2.1.0  183   -  Wed Oct 30 2024 14:31:16     INFO   [ChannelStartupService]  [string]  Group Ignore: false 
[Evolution API]  [test]  v2.1.0  183   -  Wed Oct 30 2024 14:31:18     INFO   [ChannelStartupService]  [string]  Browser: Empatia,chrome,6.8.0-1016-azure 
[Evolution API]  [test]  v2.1.0  183   -  Wed Oct 30 2024 14:31:18     INFO   [ChannelStartupService]  [string]  Baileys version env: 2,2413,51 
[Evolution API]  [test]  v2.1.0  183   -  Wed Oct 30 2024 14:31:18     INFO   [ChannelStartupService]  [string]  Group Ignore: false " Im working with Azure Cloud. I have created a Virtual Machine running ubuntu. Here is a list of things I have already tried:
- Tried installing the whole stack again in a new VM. Same result
- Tried to bump up the version to the latest available. Same result
- Tried downgrading it without breaking changes (version 2).Same Result
- Tried installing but using Caddy as a reverse proxy. Same result
- Tried opening All inbound/outbound traffic from withing azure firewall console.Same Result.
For me, it seems that somehow Azure (or maybe Traefik)  is blocking/not redirecting WebSocket traffic correctly. Making it impossible for Baileys to reach out. Has anyone faced a similar problem? 
It would help me if someone could shed some light on this. If you need any more details/ talk with me Just @ me I will be pleased.

**Comment by almirb** [comment]
I have the same problem.

**Comment by almirb** [comment]
Hi @AlejoTorres2001 !

I changed `CONFIG_SESSION_PHONE_VERSION` env variable to `2.2432.5.0` and it worked!

[Source](https://github.com/EvolutionAPI/evolution-api/issues/811#issuecomment-2308384506)

**Comment by Heretic-tripto** [comment]
CONFIG_SESSION_PHONE_VERSION=2.3000.1015901307

Works here!

**Comment by fcmiao** [comment]
worked here!

**Comment by AlejoTorres2001** [comment]
Thanks all! Yes it seems ti has something to do with CONFIG_SESSION_PHONE_VERSION, both versions mentioned work well

**Comment by jonathancostajr** [comment]
Eu consegui resolver excluindo a antiga conexão antiga no aplicativo do whatsapp e o qr code apareceu.

**Comment by dmureika** [comment]
Prueba esta versión = 2.3000.1023204200

**Comment by sergiogonzalezfreelance** [comment]
Prueba esta versión = 2.3000.1023204200

Funciona ok. Gracias!

**Comment by Denis-root** [comment]
Una forma de obtener ese valor:
[https://github.com/EvolutionAPI/evolution-api/issues/1014](url)

**Comment by Denis-root** [comment]
Una opción para obtener ese valor rapidamente:
[https://youtube.com/shorts/EoE9PNx0Klk?feature=share](url)

**Comment by tiagomatosweb** [comment]
Version 2.3000.1023204200 also worked here.
Would be good if we have any documentation to understand what is happening

**Comment by BecerrilJose** [comment]
Version 2.3000.1023204200 stop working today. Anyone having the same problem?

**Comment by BecerrilJose** [comment]
If anyone had the same error the official version now is :  2.3000.1028395461

**Comment by dan-ec05** [comment]
> If anyone had the same error the official version now is : 2.3000.1028395461

Damn, thank you mate, it just worked for me, where did you find the version? Is there a documentation or something?

**Comment by fofostudio** [comment]
Donde la encontraste como la encontramos cada que cambie ?

**Comment by BecerrilJose** [comment]
Got to WhatsApp web with any phone number, open the developer view in your web browser, normally F12, a new window will pop up in your browser, click on Console menu, and you can search there for the variable CONFIG_SESSION_PHONE_VERSION . Copy the new working value in EvolutionAPI environment variable and enjoy OpenSource forever.
🤗

**Comment by BecerrilJose** [comment]
> > If anyone had the same error the official version now is : 2.3000.1028395461
> 
> Damn, thank you mate, it just worked for me, where did you find the version? Is there a documentation or something?
Look my last comment.

**Comment by codesbandit** [comment]
> 1028395461

thanks a lot mate, how u can get web whatsapp version ?
