### ISSUE TITLE
Erro no envio de mídia na instancia WhatsApp Cloud API

### ISSUE THREAD

**Issue by AlafaethyG** [EvolutionAPI/evolution-api#1026]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

Ao realizar um envio de mídia, tipo imagem pelo WhatsApp não esta chegando no chatwoot

![img_info](https://github.com/user-attachments/assets/b5c34c7d-d121-4289-a7db-d4c8439fc0ae)

![img_info2](https://github.com/user-attachments/assets/2a07cedb-513e-4e73-a45d-011d70eabf18)

### What did you expect?

Que a imagem aparece-se no chatwoot

### What did you observe instead of what you expected?

Erros aparecendo no log de "TypeError [ERR_INVALID_ARG_TYPE]: " e "Error on upload file to minio" 

### Screenshots/Videos

![img1_err](https://github.com/user-attachments/assets/b2c2e3e6-1683-484d-8cb6-4e9167643fa3)

![img2_err](https://github.com/user-attachments/assets/a04644b7-7f64-4004-825f-d29b79d2e8f1)

### Which version of the API are you using?

Latest  = v2.2

### What is your environment?

Docker

### If applicable, paste the log output

[
  'Error on upload file to minio',
  "Cannot read properties of undefined (reading 'remoteJid')",
  "TypeError: Cannot read properties of undefined (reading 'remoteJid')\n" +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)'
    '    at ps.messageHandle (/evolution/dist/main.js:236:1914)\n' +
] 

------------------------------------------------------------------------------------------------------------------------------------------------

TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
  'Error on upload file to minio',
[Evolution API]    v2.2.0  170   -  Fri Nov 01 2024 08:39:02     ERROR   [ChatwootService]  [object]   
    at Function.from (node:buffer:320:9)
    at Ae.eventWhatsapp (/evolution/dist/main.js:123:2199)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ps.messageHandle (/evolution/dist/main.js:236:4290) {
  code: 'ERR_INVALID_ARG_TYPE'
  }

**Comment by 1kpas** [comment]
Conseguiu resolver?

**Comment by dpaes** [comment]
quando inicializa o minio @AlafaethyG ele se conecta corretamente? E outra coisa, qual o tamanho da imagem que dá problema? ou é uma extensão especifica de imagem ou midia que dá problema?

**Comment by edsonfast** [comment]
No meu caso qualquer mídia que envio pelo chatwoot não abre no WhatsApp, quando tento abrir direto no MinIO também não abre, como se estivesse corrompido, já quando enviou pelo Whastapp abre normalmente, alguém com esse problema?
