### ISSUE TITLE
IOS bugando quando tem duas pessoas interagindo com mesmo número.

### ISSUE THREAD

**Issue by lucasantoniooficial** [EvolutionAPI/evolution-api#1030]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

Com os testes feitos o bug acontece quando um número IOS feito pelo celular chama o número que está na evolution, chega nos logs da evolution dando erro e não aciona o webhook.

### What did you expect?

Esperava receber mensagens sem problemas de android e ios.

### What did you observe instead of what you expected?

A mensagem não chega e nos logs da evolution da este erro:

2024/11/03 10:42AM 50 pid=165 hostname=b42dbeaa5ab0 key={"remoteJid":"5500000000@s.whatsapp.net","fromMe":false,"id":"0000000000"} err={"type":"PreKeyError","message":"Invalid PreKey ID","stack":"PreKeyError: Invalid PreKey ID\n    at SessionBuilder.initIncoming (/evolution/node_modules/libsignal/src/session_builder.js:66:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async 556191585728.0 [as awaitable] (/evolution/node_modules/libsignal/src/session_cipher.js:205:30)\n    at async _asyncQueueExecutor (/evolution/node_modules/libsignal/src/queue_job.js:20:29)","name":"PreKeyError"} msg=failed to decrypt message

OBS: Número e Id ofuscado para não expor contato de alguém.

### Which version of the API are you using?

2.1.1

### What is your environment?

Linux

### If applicable, paste the log output

2024/11/03 10:42AM 50 pid=165 hostname=b42dbeaa5ab0 key={"remoteJid":"5500000000@s.whatsapp.net","fromMe":false,"id":"0000000000"} err={"type":"PreKeyError","message":"Invalid PreKey ID","stack":"PreKeyError: Invalid PreKey ID\n    at SessionBuilder.initIncoming (/evolution/node_modules/libsignal/src/session_builder.js:66:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async 556191585728.0 [as awaitable] (/evolution/node_modules/libsignal/src/session_cipher.js:205:30)\n    at async _asyncQueueExecutor (/evolution/node_modules/libsignal/src/queue_job.js:20:29)","name":"PreKeyError"} msg=failed to decrypt message

### Additional Notes

Não tenho cache ativo, tanto redis e local estão desativados.

**Comment by alessondejesus** [comment]
Up. Mesmo problema
