### ISSUE TITLE
Erro ao enviar mensagem de mídia

### ISSUE THREAD

**Issue by thiago-coucello** [EvolutionAPI/evolution-api#1031]
### Bem-vido!

- [X] Sim, pesquisei problemas semelhantes no [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) e não encontrei nenhum.

### O que você fez?

Enviei uma requisição para o endpoint /message/sendMedia/<instancia>.

### O que você esperava?

Esperava que a mensagem com mídia fosse enviada para o número informado

### O que vc observou ao invés do que esperava?

estou obtendo o erro:

```{json}
{
	"status": 500,
	"error": "Internal Server Error",
	"response": {
		"message": "Cannot read properties of undefined (reading 'findMany')"
	}
}
``` 

### Capturas de Tela/Vídeos

![image](https://github.com/user-attachments/assets/711b7c20-c00c-4d3f-9bbe-592a8bb6cfdd)

### Qual versão da API você está usando?

v2.1.1 - no Docker para Windows

### Qual é o seu ambiente?

Windows

### Se aplicável, cole a saída do log

O erro não gera log no container

### Notas Adicionais

Acabei de testar e estou obtendo o mesmo erro para mensagens de texto (/message/sendText/<instancia>)

_No response_

**Comment by bguetter** [comment]
Estou com o mesmo erro por aqui, ao tentar enviar mensagem fica dando o erro, ai tenho que reiniciar a stack de  tempo em tempo para voltar a conexao.

O erro aqui é:

{

  "errorMessage": "The service was not able to process your request",

  "errorDescription": "Internal Server Error",

  "errorDetails": {

    "rawErrorMessage": [

      "500 - \"{\\\"status\\\":500,\\\"error\\\":\\\"Internal Server Error\\\",\\\"response\\\":{\\\"message\\\":\\\"Connection Closed\\\"}}\""

    ],

    "httpCode": "500"

  },

  "n8nDetails": {

    "nodeName": "HTTP Request",

    "nodeType": "n8n-nodes-base.httpRequest",

    "nodeVersion": 4.2,

    "itemIndex": 0,

    "time": "24/02/2025, 10:07:56",

    "n8nVersion": "1.79.2 (Self Hosted)",

    "binaryDataMode": "default",

    "stackTrace": [

      "NodeApiError: The service was not able to process your request",

      "    at ExecuteContext.execute (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/HttpRequest/V3/HttpRequestV3.node.js:525:33)",

      "    at processTicksAndRejections (node:internal/process/task_queues:95:5)",

      "    at WorkflowExecute.runNode (/usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/execution-engine/workflow-execute.js:627:19)",

      "    at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/execution-engine/workflow-execute.js:878:51",

      "    at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/execution-engine/workflow-execute.js:1211:20"

    ]

  }

}
