### ISSUE TITLE
Erro ao criar grupo com participantes

### ISSUE THREAD

**Issue by rafwell** [EvolutionAPI/evolution-api#1042]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

Ao tentar criar um grupo com participantes.

### What did you expect?

Esperava a criação do grupo com os participantes

### What did you observe instead of what you expected?

Recebo um erro 500.

### Screenshots/Videos

![Screenshot 2024-11-06 at 18 31 39](https://github.com/user-attachments/assets/31570b7d-0918-44e6-af86-27952e3bc539)

### Which version of the API are you using?

2.2.0

### What is your environment?

Windows

### Other environment specifications

Docker

### If applicable, paste the log output

Log: 2024-11-06 18:36:22 evolution_api | [Evolution API] [minhainstancia.local.c6ace8e0-97d0-11ef-a8a5-0b8cfd192ad1] v2.1.1 163 - Wed Nov 06 2024 18:36:22 ERROR [ChannelStartupService] [string] line 3363
2024-11-06 18:36:22 evolution_api | [Evolution API] [minhainstancia.local.c6ace8e0-97d0-11ef-a8a5-0b8cfd192ad1] v2.1.1 163 - Wed Nov 06 2024 18:36:22 ERROR [ChannelStartupService] [object]
2024-11-06 18:36:22 evolution_api | TypeError: Cannot read properties of undefined (reading 'findMany')
2024-11-06 18:36:22 evolution_api | at Ko (/evolution/dist/main.js:215:6977)
2024-11-06 18:36:22 evolution_api | at Ts.whatsappNumber (/evolution/dist/main.js:233:1126)
2024-11-06 18:36:22 evolution_api | at async Ts.createGroup (/evolution/dist/main.js:233:10698)
2024-11-06 18:36:22 evolution_api | at async Gt.createGroup (/evolution/dist/main.js:2:8941)
2024-11-06 18:36:22 evolution_api | at async Ji.dataValidate (/evolution/dist/main.js:236:98590)
2024-11-06 18:36:22 evolution_api | at async /evolution/dist/main.js:236:152139
2024-11-06 18:36:22 evolution_api |

### Additional Notes

Ref #399

**Comment by rafwell** [comment]
Descobri que meu docker estava na versão 2.1.1 e não na 2.2.0 como eu havia pensado. 
Atualizei e o problema não ocorre mais na versão 2.2.0.
