### ISSUE TITLE
Evo 2.1.1 e TypeBot 3.1.0, FLuxo está conectado mas não inicia

### ISSUE THREAD

**Issue by JefersonBatistaSouza** [EvolutionAPI/evolution-api#1045]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

Fiz todas as configurações conforme a documentação, evo e typebot conectados, porém ao enviar uma mensagem no whatsapp o fluxo não inicia

### What did you expect?

Esperava que ao encaminha uma mensagem de whatsapp o fluxo inicia-se a conversação

### What did you observe instead of what you expected?

Fluxo não inicia

### Which version of the API are you using?

API V2.1

### What is your environment?

Docker

**Comment by souoberg** [comment]
Mesmo erro aqui, no log da Evolution, temos a seguinte mensagem de erro:

`maxBodyLength: -1,
env: [Object],
validateStatus: [Function: validateStatus],
headers: [Object [AxiosHeaders]],
method: 'post',
url: 'https://typebot-api.wppninja.com.br/api/v1/sendMessage',
data: '{"startParams":{"publicId":"start","prefilledVariables":{"remoteJid":"5511966695957@s.whatsapp.net","pushName":"Berg","instanceName":"Lotobanca","serverUrl":"https://api.wppninja.com.br","apiKey":"mKC4G9gdnch6QaLYysq8PZjtzN3D2RpF","ownerJid":null}}}'
},
request: <ref *1> ClientRequest {
_events: [Object: null prototype],
_eventsCount: 7,
_maxListeners: undefined,
outputData: [],
outputSize: 0,
writable: true,
destroyed: true,
_last: false,
chunkedEncoding: false,
shouldKeepAlive: true,
maxRequestsOnConnectionReached: false,
_defaultKeepAlive: true,
useChunkedEncodingByDefault: true,
sendDate: false,
_removedConnection: false,
_removedContLen: false,
_removedTE: false,
strictContentLength: false,
_contentLength: '249',
_hasBody: true,
_trailer: '',
finished: true,
_headerSent: true,
_closed: true,
socket: [TLSSocket],
_header: 'POST /api/v1/sendMessage HTTP/1.1\r\n' +
  'Accept: application/json, text/plain, */*\r\n' +
  'Content-Type: application/json\r\n' +
  'User-Agent: axios/1.7.7\r\n' +
  'Content-Length: 249\r\n' +
  'Accept-Encoding: gzip, compress, deflate, br\r\n' +
  'Host: typebot-api.wppninja.com.br\r\n' +
  'Connection: keep-alive\r\n' +
  '\r\n',
_keepAliveTimeout: 0,
_onPendingData: [Function: nop],
agent: [Agent],
socketPath: undefined,
method: 'POST',
maxHeaderSize: undefined,
insecureHTTPParser: undefined,
joinDuplicateHeaders: undefined,
path: '/api/v1/sendMessage',
_ended: true,
res: [IncomingMessage],
aborted: false,
timeoutCb: null,
upgradeOrConnect: false,
parser: null,
maxHeadersCount: null,
reusedSocket: false,
host: 'typebot-api.wppninja.com.br',
protocol: 'https:',
_redirectable: [Writable],
[Symbol(shapeMode)]: false,
[Symbol(kCapture)]: false,
[Symbol(kBytesWritten)]: 0,
[Symbol(kNeedDrain)]: false,
[Symbol(corked)]: 0,
[Symbol(kOutHeaders)]: [Object: null prototype],
[Symbol(errored)]: null,
[Symbol(kHighWaterMark)]: 16384,
[Symbol(kRejectNonStandardBodyWrites)]: false,
[Symbol(kUniqueHeaders)]: null
},
data: {
message: 'Input validation failed',
code: 'BAD_REQUEST',
data: [Object],
issues: [Array]
}
},
status: 400
} 
Erro ao processar mensagens: TypeError: h is not iterable
at u (/evolution/dist/main.js:159:74)
at nt.sendWAMessage (/evolution/dist/main.js:152:1711)
at nt.processTypebot (/evolution/dist/main.js:161:5021)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async Fs.emit (/evolution/dist/main.js:282:33378)
at async ae.emit (/evolution/dist/main.js:273:7966)
at async messages.upsert (/evolution/dist/main.js:250:22789)
[Evolution API]    v2.2.0  169   -  Mon Nov 11 2024 13:13:10     ERROR   [TypebotController]  [object]   
TypeError: Cannot read properties of undefined (reading 'messages')
at nt.processTypebot (/evolution/dist/main.js:161:5190)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async Fs.emit (/evolution/dist/main.js:282:33378)
at async ae.emit (/evolution/dist/main.js:273:7966)
at async messages.upsert (/evolution/dist/main.js:250:22789) `

**Comment by JefersonBatistaSouza** [comment]
Consegui resolver trocando a API_KEY e adicionando TYPEBOT_KEEP_ALIVE=true

Refiz a instância e deu certo

**Comment by andrekutianski** [comment]
Por aqui sem sucesso com suas dicas @JefersonBatistaSouza você trocou a `API_KEY` de quem? Typebot ou Evolution?

Testando com evolution v2.2.3 e Typebot na v3.1.2 e v3.5. Sempre retorna o seguinte erro:

```log

Erro ao processar mensagens: TypeError: m is not iterable
at l (/evolution/dist/main.js:159:74)
at at.sendWAMessage (/evolution/dist/main.js:152:1711)
at at.processTypebot (/evolution/dist/main.js:161:5021)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async Us.startBot (/evolution/dist/main.js:286:28932)
at async Mi.dataValidate (/evolution/dist/main.js:286:62716)
at async /evolution/dist/main.js:286:105868
```
Em meus testes com Typebot v3.5 a sessão foi aberta no evolution, mas o fluxo do bot definido não iniciou.

**Comment by LauroRafael** [comment]
Mesmo problema aqui.
Como resolveram?

Erro ao processar mensagens: TypeError: m is not iterable

    at l (/evolution/dist/main.js:159:74)

    at at.sendWAMessage (/evolution/dist/main.js:152:1711)

    at at.processTypebot (/evolution/dist/main.js:161:5021)

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

    at async Us.emit (/evolution/dist/main.js:286:33330)

    at async ce.emit (/evolution/dist/main.js:277:6704)

    at async messages.upsert (/evolution/dist/main.js:230:26514)

**Comment by ddavid-almeida** [comment]
Pessoal provalvemente voces pegaram uma stack em algum video no youtube. editem a stack da EVOLUTION de voces na parte do typebot remova tudo e deixe:

      - TYPEBOT_ENABLED=true
      - TYPEBOT_API_VERSION=latest

vai funcionar.

**Comment by leonardocxavier** [comment]
Mesmo erro aqui, fiz conforme orientação mas nada sem sucesso, alguem ai conseguiu resolver isso?
