### ISSUE TITLE
Bug Upload Minio META CLOUD API

### ISSUE THREAD

**Issue by 1kpas** [EvolutionAPI/evolution-api#1061]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

Ao usar a Meta Cloud API Whatsapp e Ativar o Minio tenho o seguinte problema:
[Evolution API]  [Leticia - Assistente Pessoal]  v2.2.0  183   -  Tue Nov 12 2024 17:07:44     ERROR   [ChannelStartupService]  [object]   

[

  'Error on upload file to minio',

  "Cannot read properties of undefined (reading 'remoteJid')",

  "TypeError: Cannot read properties of undefined (reading 'remoteJid')\n" +

    '    at ps.messageHandle (/evolution/dist/main.js:236:1914)\n' +

    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)'

] 

### What did you expect?

Ao enviar um audio em tese ele teria que salvar

### What did you observe instead of what you expected?

Ele aconteceu esse erro:
[Evolution API]  [Leticia - Assistente Pessoal]  v2.2.0  183   -  Tue Nov 12 2024 17:07:44     ERROR   [ChannelStartupService]  [object]   

[

  'Error on upload file to minio',

  "Cannot read properties of undefined (reading 'remoteJid')",

  "TypeError: Cannot read properties of undefined (reading 'remoteJid')\n" +

    '    at ps.messageHandle (/evolution/dist/main.js:236:1914)\n' +

    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)'

] 

### Screenshots/Videos

![image](https://github.com/user-attachments/assets/38267e3d-23a9-499a-86c8-b739ac96a597)

### Which version of the API are you using?

Released

### What is your environment?

Other

**Comment by otavio-marco** [comment]
Tenho o mesmo problema aqui. identico

**Comment by lucacasanova** [comment]
tenho o mesmo problema aqui

**Comment by diegoirs23** [comment]
Conseguiram resolver?

**Comment by EvandroCaruso** [comment]
Nenhuma novidade pessoal? 
Estou com o mesmo problema.  Para alguém está funcionando? Alguma versão?

**Comment by oristides** [comment]
Memso problema.. conseguiram resolver?

**Comment by oristides** [comment]
@lucacasanova @diegoirs23  Conseguiram resolver o problema? eu testei com s3 e com minio e os 2 dá o mesmo erro. Será que tem a ver com versões novas do Chatwoot. Somentes messages via Chatwoot que nâo estão funcionando. Isso acontece no CLOUD API especificamente?


Teste as variaveis de ambiente 
WA_BUSINESS_VERSION=v21.0 
v22.0 e 20.0 Sem resultado algum.

**Comment by guigagb** [comment]
@DavidsonGomes foi resolvido em alguma versão específica? estou com o mesmo erro na 2.2.3, estava funcionando normalmente e parou de funcionar.
