### ISSUE TITLE
rate-overlimit ao enviar mensagens para grupos

### ISSUE THREAD

**Issue by jeffersonfelixdev** [EvolutionAPI/evolution-api#1089]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

Ao enviar uma quantidade de mensagens para grupos (eu testei com 5 a 6 grupos), mesmo com um intervalo de 10 a 20 segundos entre as mensagens, em alguns momentos ocorre o seguinte erro:

```
Error: rate-overlimit
  at assertNodeErrorFree (/evolution/node_modules/baileys/lib/WABinary/generic-utils.js:56:15)
  at query (/evolution/node_modules/baileys/lib/Socket/socket.js:143:48)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async Object.groupMetadata (/evolution/node_modules/baileys/lib/Socket/groups.js:22:24)
  at async Rs.updateGroupMetadataCache (/evolution/dist/main.js:271:10277)
```

Isso ocorre com muito mais frequência em comunidades ("isCommunity: true")

### What did you expect?

Enviar mensagens para grupos

### What did you observe instead of what you expected?

Erro 429 no envio de algumas mensagens

### Which version of the API are you using?

2.2.0

### What is your environment?

Docker

### Other environment specifications

Evolution API v2.2.0 com CACHE_LOCAL habilitado

**Comment by GustavoGSA** [comment]
Também estou com esse problema, alguma solução?

**Comment by MarcosSarges** [comment]
Estou recebendo esse erro ao tentar listar os grupos

**Comment by emelo7** [comment]
Estou na v2.2.3 e estou recebendo o mesmo erro, também relacionado a listar grupos com participantes (Fetch All Groups).
O engraçado é que quando faço a requisição via Postman, mesmo o log do server apresentando o erro, ele retorna os dados dos grupos.

**Comment by jeffersonfelixdev** [comment]
Resolvi escrever minha própria API.

Evolution até atende em alguns cenários, mas a série de problemas principalmente com grupos e banimentos inesperados me fez tomar essa decisão.

E deu tão certo que agora estou com um SaaS.

Caso tenha interesse: https://ZapperAPI.com

**Comment by whyrnld** [comment]
aqui estou com o mesmo erro, porem ao tentar remover participantes dos grupos

```
[Evolution API]  [Envios1]  v2.2.3  240   -  Wed Jun 18 2025 07:14:01     ERROR   [ChannelStartupService]  [object]   
Error: rate-overlimit
    at assertNodeErrorFree (/evolution/node_modules/baileys/lib/WABinary/generic-utils.js:56:15)
    at query (/evolution/node_modules/baileys/lib/Socket/socket.js:143:48)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.groupMetadata (/evolution/node_modules/baileys/lib/Socket/groups.js:22:24)
    at async Rs.updateGroupMetadataCache (/evolution/dist/main.js:251:10357) {


  data: 429,
  isBoom: true,
  isServer: true,
  output: {
    statusCode: 500,
    payload: {
      statusCode: 500,
      error: 'Internal Server Error',
      message: 'An internal server error occurred'
    },
    headers: {}
  }
} 
```

**Comment by luispimenta** [comment]
alguém resolveu essa questão?

**Comment by GustavoGSA** [comment]
> alguém resolveu essa questão?

ixi nem sei amigo, eu cheguei ao ponto extremo da raiva e fiz minha própria API, evolution da não muita dor de cabeça. rs
