### ISSUE TITLE
Não aparece a caixa de entrada no chatwoot criado no manager v1.5.2

### ISSUE THREAD

**Issue by luiztonucci** [EvolutionAPI/evolution-api#162]
Bom dia @DavidsonGomes, quando crio a caixa de entrada pelo manager, não aparece no chatwoot. Tento criar por fora tbm não está aparecendo. Estou usando a v.1.5.2

**Comment by maaper** [comment]
Hi there! same issue here.
After running this: `{{baseUrl}}/instance/create`

With this body:
```
{
    "instanceName": "{{instanceChatwoot}}",
    "token": "123456",
    "qrcode": true,
    "chatwoot_account_id": {{ChatwootID}},
    "chatwoot_token": "{{tokenChatwoot}}",
    "chatwoot_url": "{{ChatwootUrl}}",
    "chatwoot_sign_msg": true,
    "chatwoot_reopen_conversation": true,
    "chatwoot_conversation_pending": false
}
```

I get this message:
![image](https://github.com/EvolutionAPI/evolution-api/assets/56989894/891a122f-f030-4480-9cfd-729c7aa50379)

And this result:
```
{
    "instance": {
        "instanceName": "instanceChatwoot",
        "status": "created"
    },
    "hash": {
        "apikey": "123456"
    },
    "webhook": {},
    "websocket": {},
    "rabbitmq": {},
    "typebot": {
        "enabled": false
    },
    "settings": {
        "reject_call": false,
        "msg_call": "",
        "groups_ignore": false,
        "always_online": false,
        "read_messages": false,
        "read_status": false
    },
    "chatwoot": {
        "enabled": true,
        "account_id": 1,
        "token": "8X8rayepXgZj6rUdoiSW9teg",
        "url": "https://chatwooturl.me",
        "sign_msg": true,
        "reopen_conversation": true,
        "conversation_pending": false,
        "name_inbox": "instanceChatwoot",
        "webhook_url": "https://evolutionapiurl.me/chatwoot/webhook/instanceChatwoot"
    }
}
```

However, not inbox it's being generated on chatwoot.
And what is more strange, if I run this method `{{baseUrl}}/instance/fetchInstances`, I didn't receive the new instance created for chatwoot. It seems that there could be something wrong with that method.

**Comment by joelmartins** [comment]
Same error here!

**Comment by maaper** [comment]
Quite strange. Let wait for someone to help.

**Comment by joelmartins** [comment]
I´m solved setting underscores_in_headers on in [NGINX config](http://nginx.org/en/docs/http/ngx_http_core_module.html#underscores_in_headers).

**Comment by maaper** [comment]
> I´m solved setting underscores_in_headers on in [NGINX config](http://nginx.org/en/docs/http/ngx_http_core_module.html#underscores_in_headers).

I'm not using NGINX, could you give me more information about your solution

Now i realise the logs of EVOLUTION API with this error, but I can not understand the error and possible solution.

```
[Evolution API]  v1.5.4  1   -  Fri Oct 13 2023 12:12:00     ERROR   [unhandledRejection]  [object]   
{
  origin: Promise {
    <rejected> ApiError: Unauthorized
        at catchErrorCodes (/evolution/node_modules/@figuro/chatwoot-sdk/dist/core/request.js:226:15)
        at /evolution/node_modules/@figuro/chatwoot-sdk/dist/core/request.js:257:17
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
      url: 'https://chatwoot.mydns.me/api/v1/accounts/1/inboxes',
      status: 401,
      statusText: 'Unauthorized',
      body: [Object],
      request: [Object]
    }
  },

  stderr: 2,
  error: ApiError: Unauthorized
      at catchErrorCodes (/evolution/node_modules/@figuro/chatwoot-sdk/dist/core/request.js:226:15)
      at /evolution/node_modules/@figuro/chatwoot-sdk/dist/core/request.js:257:17
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
    url: 'https://chatwoot.mydns.me/api/v1/accounts/1/inboxes',
    status: 401,
    statusText: 'Unauthorized',
    body: { errors: [Array] },
    request: {
      method: 'GET',
      url: '/api/v1/accounts/{account_id}/inboxes',
      path: [Object],
      errors: [Object]
    }
  }
} 
```
