### ISSUE TITLE
 Alguém ja teve esse erro? AxiosError: socket hang up 

### ISSUE THREAD

**Issue by bergpinheiro** [EvolutionAPI/evolution-api#234]
[Evolution API]  v1.5.4  1   -  Mon Dec 04 2023 08:35:16     ERROR   [unhandledRejection]  [object]   
{
  origin: Promise {
    <rejected> AxiosError: socket hang up
        at AxiosError.from (file:///evolution/node_modules/axios/lib/core/AxiosError.js:89:14)
        at RedirectableRequest.handleRequestError (file:///evolution/node_modules/axios/lib/adapters/http.js:593:25)
        at RedirectableRequest.emit (node:events:514:28)
        at eventHandlers.<computed> (/evolution/node_modules/follow-redirects/index.js:14:24)
        at ClientRequest.emit (node:events:514:28)
        at TLSSocket.socketOnEnd (node:_http_client:519:9)
        at TLSSocket.emit (node:events:526:35)
        at endReadableNT (node:internal/streams/readable:1376:12)
        at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
      code: 'ECONNRESET',
      config: [Object],
      request: [Writable],
      cause: [Error]
    }
  },

  stderr: 2,
  error: AxiosError: socket hang up
      at AxiosError.from (file:///evolution/node_modules/axios/lib/core/AxiosError.js:89:14)
      at RedirectableRequest.handleRequestError (file:///evolution/node_modules/axios/lib/adapters/http.js:593:25)
      at RedirectableRequest.emit (node:events:514:28)
      at eventHandlers.<computed> (/evolution/node_modules/follow-redirects/index.js:14:24)
      at ClientRequest.emit (node:events:514:28)
      at TLSSocket.socketOnEnd (node:_http_client:519:9)
      at TLSSocket.emit (node:events:526:35)
      at endReadableNT (node:internal/streams/readable:1376:12)
      at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
    code: 'ECONNRESET',
    config: {
      transitional: [Object],
      adapter: [Array],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: Infinity,
      maxBodyLength: Infinity,
      env: [Object],
      validateStatus: [Function: validateStatus],
      headers: [Object [AxiosHeaders]],
      responseType: 'stream',
      method: 'get',
      url: 'https://mmg.whatsapp.net/o1/v/t62.7118-24/f1/m233/up-oil-image-3e292304-cf41-4f5d-b202-f75bcc101d2c?ccb=9-4&oh=01_AdTkKdkyRpM8fBqrUCP6Cp3QJkVaeRkY9nmqemqMhU9XKA&oe=659526C3&_nc_sid=000000&mms3=true',
      data: undefined
    },
    request: Writable {
      _writableState: [WritableState],
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      _options: [Object],
      _ended: true,
      _ending: true,
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 0,
      _requestBodyBuffers: [],
      _onNativeResponse: [Function (anonymous)],
      _currentRequest: [ClientRequest],
      _currentUrl: 'https://mmg.whatsapp.net/o1/v/t62.7118-24/f1/m233/up-oil-image-3e292304-cf41-4f5d-b202-f75bcc101d2c?ccb=9-4&oh=01_AdTkKdkyRpM8fBqrUCP6Cp3QJkVaeRkY9nmqemqMhU9XKA&oe=659526C3&_nc_sid=000000&mms3=true',
      [Symbol(kCapture)]: false
    },
    cause: Error: socket hang up
        at connResetException (node:internal/errors:720:14)
        at TLSSocket.socketOnEnd (node:_http_client:519:23)
        at TLSSocket.emit (node:events:526:35)
        at endReadableNT (node:internal/streams/readable:1376:12)
        at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
      code: 'ECONNRESET'
    }
  }
}

**Comment by DavidsonGomes** [comment]
Esse erro tem a ver com a cloudflare ok? verifica se esta habilitado o proxy la, esse problema acontece quando fica mais de 100 segundos sem interação no socket, não é problema da Evolution

**Comment by lindenbergp** [comment]
Nao uso o proxy lá nao. Obrigado pela resposta. Minha intenção e sempre que me deparar com um erro postar, ja que nao sou programador pelo menos contribui com logs.
