### ISSUE TITLE
Typebot 2.20 com problemas com Evo 1.6

### ISSUE THREAD

**Issue by stgcompany** [EvolutionAPI/evolution-api#282]
> Problema apresentando no meu ambiente de testes localhost, sendo evo na 8080 e typebot 3001 viewer e 3002 builder.

Já defini no `env.yml` da api do typebot como latest, e quando "starto" uma sessão ele até pega (menos o pushName que não pega mesmo declarando no body do request) porém as variáveis armazenadas no typebot não são enviadas na mensagem pelo evolution.

E pior ainda no caso de não forçar o início com o request na api, ou seja, quando o usuário manda uma mensagem... O que ocorre o seguinte erro:

<details>
  <summary>pm2 log:</summary>

```bash
0|ApiEvolution  | [Evolution API]  v1.6.0  6196   -  Fri Dec 15 2023 11:14:06     ERROR   [TypebotService]  [object]
0|ApiEvolution  | AxiosError: connect ECONNREFUSED 127.0.0.1:80
0|ApiEvolution  |     at AxiosError.from (/root/evolution-api/node_modules/axios/dist/node/axios.cjs:837:14)
0|ApiEvolution  |     at RedirectableRequest.handleRequestError (/root/evolution-api/node_modules/axios/dist/node/axios.cjs:3029:25)
0|ApiEvolution  |     at RedirectableRequest.emit (node:events:514:28)
0|ApiEvolution  |     at RedirectableRequest.emit (node:domain:488:12)
0|ApiEvolution  |     at eventHandlers.<computed> (/root/evolution-api/node_modules/follow-redirects/index.js:14:24)
0|ApiEvolution  |     at ClientRequest.emit (node:events:514:28)
0|ApiEvolution  |     at ClientRequest.emit (node:domain:488:12)
0|ApiEvolution  |     at Socket.socketErrorListener (node:_http_client:495:9)
0|ApiEvolution  |     at Socket.emit (node:events:514:28)
0|ApiEvolution  |     at Socket.emit (node:domain:488:12) {
0|ApiEvolution  |   port: 80,
0|ApiEvolution  |   address: '127.0.0.1',
0|ApiEvolution  |   syscall: 'connect',
0|ApiEvolution  |   code: 'ECONNREFUSED',
0|ApiEvolution  |   errno: -111,
0|ApiEvolution  |   config: {
0|ApiEvolution  |     transitional: {
0|ApiEvolution  |       silentJSONParsing: true,
0|ApiEvolution  |       forcedJSONParsing: true,
0|ApiEvolution  |       clarifyTimeoutError: false
0|ApiEvolution  |     },
0|ApiEvolution  |     adapter: [ 'xhr', 'http' ],
0|ApiEvolution  |     transformRequest: [ [Function: transformRequest] ],
0|ApiEvolution  |     transformResponse: [ [Function: transformResponse] ],
0|ApiEvolution  |     timeout: 0,
0|ApiEvolution  |     xsrfCookieName: 'XSRF-TOKEN',
0|ApiEvolution  |     xsrfHeaderName: 'X-XSRF-TOKEN',
0|ApiEvolution  |     maxContentLength: -1,
0|ApiEvolution  |     maxBodyLength: -1,
0|ApiEvolution  |     env: { FormData: [Function], Blob: [class Blob] },
0|ApiEvolution  |     validateStatus: [Function: validateStatus],
0|ApiEvolution  |     headers: Object [AxiosHeaders] {
0|ApiEvolution  |       Accept: 'application/json, text/plain, */*',
0|ApiEvolution  |       'Content-Type': 'application/json',
0|ApiEvolution  |       'User-Agent': 'axios/1.6.0',
0|ApiEvolution  |       'Content-Length': '18',
0|ApiEvolution  |       'Accept-Encoding': 'gzip, compress, deflate, br'
0|ApiEvolution  |     },
0|ApiEvolution  |     method: 'post',
0|ApiEvolution  |     url: 'undefined/api/v1/sessions/clq6pmzh40009mk0fkbhiw8c7/continueChat',
0|ApiEvolution  |     data: '{"message":"Olá"}'
0|ApiEvolution  |   },
0|ApiEvolution  |   request: <ref *1> Writable {
0|ApiEvolution  |     _writableState: WritableState {
0|ApiEvolution  |       state: 802924,
0|ApiEvolution  |       highWaterMark: 16384,
0|ApiEvolution  |       defaultEncoding: 'utf8',
0|ApiEvolution  |       length: 0,
0|ApiEvolution  |       corked: 0,
0|ApiEvolution  |       onwrite: [Function: bound onwrite],
0|ApiEvolution  |       writecb: null,
0|ApiEvolution  |       writelen: 0,
0|ApiEvolution  |       afterWriteTickInfo: null,
0|ApiEvolution  |       buffered: [],
0|ApiEvolution  |       bufferedIndex: 0,
0|ApiEvolution  |       pendingcb: 0,
0|ApiEvolution  |       errored: null,
0|ApiEvolution  |       [Symbol(kOnFinished)]: []
0|ApiEvolution  |     },
0|ApiEvolution  |     _events: [Object: null prototype] {
0|ApiEvolution  |       response: [Function: handleResponse],
0|ApiEvolution  |       error: [Function: handleRequestError],
0|ApiEvolution  |       socket: [Function: handleRequestSocket]
0|ApiEvolution  |     },
0|ApiEvolution  |     _eventsCount: 3,
0|ApiEvolution  |     _maxListeners: undefined,
0|ApiEvolution  |     _options: {
0|ApiEvolution  |       maxRedirects: 21,
0|ApiEvolution  |       maxBodyLength: Infinity,
0|ApiEvolution  |       protocol: 'http:',
0|ApiEvolution  |       path: '/undefined/api/v1/sessions/clq6pmzh40009mk0fkbhiw8c7/continueChat',
0|ApiEvolution  |       method: 'POST',
0|ApiEvolution  |       headers: [Object: null prototype],
0|ApiEvolution  |       agents: [Object],
0|ApiEvolution  |       auth: undefined,
0|ApiEvolution  |       family: undefined,
0|ApiEvolution  |       beforeRedirect: [Function: dispatchBeforeRedirect],
0|ApiEvolution  |       beforeRedirects: [Object],
0|ApiEvolution  |       hostname: 'localhost',
0|ApiEvolution  |       port: '',
0|ApiEvolution  |       agent: undefined,
0|ApiEvolution  |       nativeProtocols: [Object],
0|ApiEvolution  |       pathname: '/undefined/api/v1/sessions/clq6pmzh40009mk0fkbhiw8c7/continueChat'
0|ApiEvolution  |     },
0|ApiEvolution  |     _ended: false,
0|ApiEvolution  |     _ending: true,
0|ApiEvolution  |     _redirectCount: 0,
0|ApiEvolution  |     _redirects: [],
0|ApiEvolution  |     _requestBodyLength: 18,
0|ApiEvolution  |     _requestBodyBuffers: [ [Object] ],
0|ApiEvolution  |     _onNativeResponse: [Function (anonymous)],
0|ApiEvolution  |     _currentRequest: ClientRequest {
0|ApiEvolution  |       _events: [Object: null prototype],
0|ApiEvolution  |       _eventsCount: 7,
0|ApiEvolution  |       _maxListeners: undefined,
0|ApiEvolution  |       outputData: [],
0|ApiEvolution  |       outputSize: 0,
0|ApiEvolution  |       writable: true,
0|ApiEvolution  |       destroyed: false,
0|ApiEvolution  |       _last: false,
0|ApiEvolution  |       chunkedEncoding: false,
0|ApiEvolution  |       shouldKeepAlive: true,
0|ApiEvolution  |       maxRequestsOnConnectionReached: false,
0|ApiEvolution  |       _defaultKeepAlive: true,
0|ApiEvolution  |       useChunkedEncodingByDefault: true,
0|ApiEvolution  |       sendDate: false,
0|ApiEvolution  |       _removedConnection: false,
0|ApiEvolution  |       _removedContLen: false,
0|ApiEvolution  |       _removedTE: false,
0|ApiEvolution  |       strictContentLength: false,
0|ApiEvolution  |       _contentLength: '18',
0|ApiEvolution  |       _hasBody: true,
0|ApiEvolution  |       _trailer: '',
0|ApiEvolution  |       finished: false,
0|ApiEvolution  |       _headerSent: true,
0|ApiEvolution  |       _closed: false,
0|ApiEvolution  |       socket: [Socket],
0|ApiEvolution  |       _header: 'POST /undefined/api/v1/sessions/clq6pmzh40009mk0fkbhiw8c7/continueChat HTTP/1.1\r\n' +
0|ApiEvolution  |         'Accept: application/json, text/plain, */*\r\n' +
0|ApiEvolution  |         'Content-Type: application/json\r\n' +
0|ApiEvolution  |         'User-Agent: axios/1.6.0\r\n' +
0|ApiEvolution  |         'Content-Length: 18\r\n' +
0|ApiEvolution  |         'Accept-Encoding: gzip, compress, deflate, br\r\n' +
0|ApiEvolution  |         'Host: localhost\r\n' +
0|ApiEvolution  |         'Connection: keep-alive\r\n' +
0|ApiEvolution  |         '\r\n',
0|ApiEvolution  |       _keepAliveTimeout: 0,
0|ApiEvolution  |       _onPendingData: [Function: nop],
0|ApiEvolution  |       agent: [Agent],
0|ApiEvolution  |       socketPath: undefined,
0|ApiEvolution  |       method: 'POST',
0|ApiEvolution  |       maxHeaderSize: undefined,
0|ApiEvolution  |       insecureHTTPParser: undefined,
0|ApiEvolution  |       joinDuplicateHeaders: undefined,
0|ApiEvolution  |       path: '/undefined/api/v1/sessions/clq6pmzh40009mk0fkbhiw8c7/continueChat',
0|ApiEvolution  |       _ended: false,
0|ApiEvolution  |       res: null,
0|ApiEvolution  |       aborted: false,
0|ApiEvolution  |       timeoutCb: [Function: emitRequestTimeout],
0|ApiEvolution  |       upgradeOrConnect: false,
0|ApiEvolution  |       parser: null,
0|ApiEvolution  |       maxHeadersCount: null,
0|ApiEvolution  |       reusedSocket: false,
0|ApiEvolution  |       host: 'localhost',
0|ApiEvolution  |       protocol: 'http:',
0|ApiEvolution  |       _redirectable: [Circular *1],
0|ApiEvolution  |       [Symbol(kCapture)]: false,
0|ApiEvolution  |       [Symbol(kBytesWritten)]: 0,
0|ApiEvolution  |       [Symbol(kNeedDrain)]: false,
0|ApiEvolution  |       [Symbol(corked)]: 0,
0|ApiEvolution  |       [Symbol(kOutHeaders)]: [Object: null prototype],
0|ApiEvolution  |       [Symbol(errored)]: null,
0|ApiEvolution  |       [Symbol(kHighWaterMark)]: 16384,
0|ApiEvolution  |       [Symbol(kRejectNonStandardBodyWrites)]: false,
0|ApiEvolution  |       [Symbol(kUniqueHeaders)]: null
0|ApiEvolution  |     },
0|ApiEvolution  |     _currentUrl: 'http://localhost/undefined/api/v1/sessions/clq6pmzh40009mk0fkbhiw8c7/continueChat',
0|ApiEvolution  |     [Symbol(kCapture)]: false
0|ApiEvolution  |   },
0|ApiEvolution  |   cause: Error: connect ECONNREFUSED 127.0.0.1:80
0|ApiEvolution  |       at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16) {
0|ApiEvolution  |     errno: -111,
0|ApiEvolution  |     code: 'ECONNREFUSED',
0|ApiEvolution  |     syscall: 'connect',
0|ApiEvolution  |     address: '127.0.0.1',
0|ApiEvolution  |     port: 80
0|ApiEvolution  |   }
0|ApiEvolution  | }
```
</details>

Podemos ver que ele tá pegando uma parte do caminho da url como `undefined`:

`_currentUrl: 'http://localhost/undefined/api/v1/sessions/clq6pmzh40009mk0fkbhiw8c7/continueChat',`

E creio que este deve ser o motivo do problema, cheguei a olhar no código e creio ser esta parte responsável:

![image](https://github.com/EvolutionAPI/evolution-api/assets/143809393/a620f24b-4e64-405e-beb0-70bf500eecf3)

**Comment by stgcompany** [comment]
Atualizei com as últimas mudanças da develop (1.6.1) e resolveu-se a maioria dos problemas, só tive depois que ir no `typebot.service.ts` na linha 737 tive que mudar de:

```js
urlTypebot = `${data.url}/api/v1/sessions/${data.sessionId}/continueChat`;
```

Para:

```js
urlTypebot = `${url}/api/v1/sessions/${data.sessionId}/continueChat`;
```

Pois antes ele identificava o `data.url` como undefined e agora sendo a url direta tá funcionando normal.
