### ISSUE TITLE
[PT][BUG]

### ISSUE THREAD

**Issue by olaronymax** [EvolutionAPI/evolution-api#376]
#### Descrição:
Ao configurar o chatwoot para reabrir conversa ou conversas de grupos está apresentando um erro no console, informando que que a conversa não foi encontrada.

`4|Evo  | [Evolution API]  v1.6.1  94793   -  Mon Jan 22 2024 14:29:46     VERBOSE   [ChatwootService]  [string]  get contact conversations in chatwoot 
4|Evo  | [Evolution API]  v1.6.1  94793   -  Mon Jan 22 2024 14:29:46     ERROR   [ChatwootService]  [object]   
4|Evo  | TypeError: Cannot read properties of undefined (reading 'id')
4|Evo  |     at ChatwootService.<anonymous> (/home/evolution/dist/src/whatsapp/services/chatwoot.service.js:433:62)
4|Evo  |     at Generator.next (<anonymous>)
4|Evo  |     at fulfilled (/home/evolution/dist/src/whatsapp/services/chatwoot.service.js:5:58)
4|Evo  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) 
4|Evo  | [Evolution API]  v1.6.1  94793   -  Mon Jan 22 2024 14:29:46     WARN   [ChatwootService]  [string]  conversation not found 
4|Evo  | [Evolution API]  v1.6.1  94793   -  Mon Jan 22 2024 14:29:46     VERBOSE   [WAStartupService]  [string]  Inserting message in database `

O contato é criado no Chatwoot mas não cria a conversa ou usa a existente.

#### Passos para Reproduzir:
1. Configure o endpoint do Chatwoot com a opção reabrir conversa ou permita conversa em grupo.

#### Capturas de Tela/Vídeos:
<img width="1172" alt="Captura de Tela 2024-01-22 às 14 34 35" src="https://github.com/EvolutionAPI/evolution-api/assets/21220721/5a465da8-6902-4201-a280-ac0da9926141">

#### Ambiente:
- **Servidor:** Ubuntu 22
- **Versão da API:** 1.6.1

#### Notas Adicionais:
Este comportamento só acontece na nova versão, mesmo que a 3.3.1 encontra-se estável a mudanção não foi tão drástica, está sendo usado o Token de usuário sem ser super admin.

**Comment by diegofrodrigues** [comment]
Tive o mesmo problema, resolvi desmarcando a opção response_bot em Accounts no admin console.

Chatwoot v3.5.2
EvolulionAPI v1.6.1
Ubuntu Server 22.04

![chatwoot](https://github.com/EvolutionAPI/evolution-api/assets/132621774/2b2ed6f8-3db4-4039-9a9a-98e1d97c2c71)
