### ISSUE TITLE
[PT][BUG] Erro 400 no endpoint sendStatus

### ISSUE THREAD

**Issue by Nilbertocs** [EvolutionAPI/evolution-api#383]
#### Descrição:
Estou tentando automatizar alguns Status mas qualquer tipo (Texto, imagem, etc) não funciona, retorna o erro abaixo

`{
    "status": 400,
    "error": "Bad Request",
    "response": {
        "message": [
            "TypeError: Cannot read properties of undefined (reading 'contextInfo')"
        ]
    }
}`

#### Ambiente:
- **Servidor:** Ubuntu 20.04
- **Versão da API:** 1.6.0

#### Envio de Logs:
2|ApiEvolution  | [Evolution API]  v1.6.0  807590   -  Sun Jan 28 2024 05:45:48     VERBOSE   [AuthRepository]  [string]  finding auth 
2|ApiEvolution  | [Evolution API]  v1.6.0  807590   -  Sun Jan 28 2024 05:45:48     VERBOSE   [AuthRepository]  [string]  finding auth in store 
2|ApiEvolution  | [Evolution API]  v1.6.0  807590   -  Sun Jan 28 2024 05:45:48     VERBOSE   [MessageRouter]  [string]  request received in sendStatus 
2|ApiEvolution  | [Evolution API]  v1.6.0  807590   -  Sun Jan 28 2024 05:45:48     VERBOSE   [MessageRouter]  [string]  request body:  
2|ApiEvolution  | [Evolution API]  v1.6.0  807590   -  Sun Jan 28 2024 05:45:48     VERBOSE   [MessageRouter]  [object]   
2|ApiEvolution  | {
2|ApiEvolution  |   statusMessage: {
2|ApiEvolution  |     type: 'image',
2|ApiEvolution  |     content: 'https://nnetwork.net/assets/img/nnetwork-logo.png',
2|ApiEvolution  |     caption: 'Teste dgdf gdfg dfgdf g dg dfg',
2|ApiEvolution  |     allContacts: true
2|ApiEvolution  |   }
2|ApiEvolution  | } 
2|ApiEvolution  | [Evolution API]  v1.6.0  807590   -  Sun Jan 28 2024 05:45:48     VERBOSE   [MessageRouter]  [string]  request query:  
2|ApiEvolution  | [Evolution API]  v1.6.0  807590   -  Sun Jan 28 2024 05:45:48     VERBOSE   [MessageRouter]  [object]   
2|ApiEvolution  | {} 
2|ApiEvolution  | [Evolution API]  v1.6.0  807590   -  Sun Jan 28 2024 05:45:48     VERBOSE   [MessageRouter]  [string]  requested sendStatus from NNetwork instance 
2|ApiEvolution  | [Evolution API]  v1.6.0  807590   -  Sun Jan 28 2024 05:45:48     VERBOSE   [WAStartupService]  [string]  Sending status message 
2|ApiEvolution  | [Evolution API]  v1.6.0  807590   -  Sun Jan 28 2024 05:45:48     VERBOSE   [WAStartupService]  [string]  Formatting status message 
2|ApiEvolution  | [Evolution API]  v1.6.0  807590   -  Sun Jan 28 2024 05:45:48     VERBOSE   [WAStartupService]  [string]  All contacts defined as true 
2|ApiEvolution  | [Evolution API]  v1.6.0  807590   -  Sun Jan 28 2024 05:45:48     VERBOSE   [WAStartupService]  [string]  Getting contacts from database 
2|ApiEvolution  | [Evolution API]  v1.6.0  807590   -  Sun Jan 28 2024 05:45:48     VERBOSE   [ContactRepository]  [string]  finding contacts 
2|ApiEvolution  | [Evolution API]  v1.6.0  807590   -  Sun Jan 28 2024 05:45:48     VERBOSE   [ContactRepository]  [string]  finding contacts in store 
2|ApiEvolution  | [Evolution API]  v1.6.0  807590   -  Sun Jan 28 2024 05:45:48     VERBOSE   [ContactRepository]  [string]  finding contacts in store by owner 
2|ApiEvolution  | [Evolution API]  v1.6.0  807590   -  Sun Jan 28 2024 05:45:48     VERBOSE   [ContactRepository]  [string]  contacts found in store: 1 contacts 
2|ApiEvolution  | [Evolution API]  v1.6.0  807590   -  Sun Jan 28 2024 05:45:48     VERBOSE   [WAStartupService]  [string]  Getting contacts with push name 
2|ApiEvolution  | [Evolution API]  v1.6.0  807590   -  Sun Jan 28 2024 05:45:48     VERBOSE   [WAStartupService]  [object]   
2|ApiEvolution  | [] 
2|ApiEvolution  | [Evolution API]  v1.6.0  807590   -  Sun Jan 28 2024 05:45:48     VERBOSE   [WAStartupService]  [string]  Type defined as image 
2|ApiEvolution  | [Evolution API]  v1.6.0  807590   -  Sun Jan 28 2024 05:45:48     VERBOSE   [WAStartupService]  [string]  Sending message with typing 
2|ApiEvolution  | [Evolution API]  v1.6.0  807590   -  Sun Jan 28 2024 05:45:48     VERBOSE   [WAStartupService]  [string]  Check if number "status@broadcast" is WhatsApp 
2|ApiEvolution  | [Evolution API]  v1.6.0  807590   -  Sun Jan 28 2024 05:45:48     VERBOSE   [WAStartupService]  [string]  Getting whatsapp number 
2|ApiEvolution  | [Evolution API]  v1.6.0  807590   -  Sun Jan 28 2024 05:45:48     VERBOSE   [WAStartupService]  [string]  Creating jid with number: status@broadcast 
2|ApiEvolution  | [Evolution API]  v1.6.0  807590   -  Sun Jan 28 2024 05:45:48     VERBOSE   [WAStartupService]  [string]  Number already contains @broadcast 
2|ApiEvolution  | [Evolution API]  v1.6.0  807590   -  Sun Jan 28 2024 05:45:48     VERBOSE   [WAStartupService]  [string]  Exists: "false" | jid: +status@broadcast 
2|ApiEvolution  | [Evolution API]  v1.6.0  807590   -  Sun Jan 28 2024 05:45:48     VERBOSE   [WAStartupService]  [string]  Sending message 
2|ApiEvolution  | [Evolution API]  v1.6.0  807590   -  Sun Jan 28 2024 05:45:48     ERROR   [WAStartupService]  [object]   
2|ApiEvolution  | TypeError: Cannot read properties of undefined (reading 'contextInfo')
2|ApiEvolution  |     at generateForwardMessageContent (/root/evolution-api/node_modules/@whiskeysockets/baileys/lib/Utils/messages.js:222:37)
2|ApiEvolution  |     at generateWAMessageContent (/root/evolution-api/node_modules/@whiskeysockets/baileys/lib/Utils/messages.js:302:55)
2|ApiEvolution  |     at generateWAMessage (/root/evolution-api/node_modules/@whiskeysockets/baileys/lib/Utils/messages.js:507:102)
2|ApiEvolution  |     at Object.sendMessage (/root/evolution-api/node_modules/@whiskeysockets/baileys/lib/Socket/messages-send.js:614:69)
2|ApiEvolution  |     at WAStartupService.<anonymous> (/root/evolution-api/dist/src/whatsapp/services/whatsapp.service.js:1984:54)
2|ApiEvolution  |     at Generator.next (<anonymous>)
2|ApiEvolution  |     at /root/evolution-api/dist/src/whatsapp/services/whatsapp.service.js:31:71
2|ApiEvolution  |     at new Promise (<anonymous>)
2|ApiEvolution  |     at __awaiter (/root/evolution-api/dist/src/whatsapp/services/whatsapp.service.js:27:12)
2|ApiEvolution  |     at /root/evolution-api/dist/src/whatsapp/services/whatsapp.service.js:1964:50

**Comment by Nilbertocs** [comment]
Notei que já existe uma issue sobre, fechando a duplicata!
https://github.com/EvolutionAPI/evolution-api/issues/100
