### ISSUE TITLE
[PT][BUG] Chatwoot envia msg, mas não recebe

### ISSUE THREAD

**Issue by leandrobtu** [EvolutionAPI/evolution-api#470]
#### Descrição:
Atualizei o Evolution da versão 1.6.0 pra 1.7.0 e agora eu consigo enviar as mensagens pelo chatwoot normalmente mas quando envio do celular pra ele a msg nao chega  e gera um erro no log do evolution, nao estou conseguindo decifrar o erro, segue abaixo

#### Passos para Reproduzir:
Enviar uma msg do whats para o celular cadastrado no chatwoot

#### Comportamento Esperado:
que a msg chegue, porem ele mostra no contador que algo chegou mas nada aparece na tela

#### Comportamento Atual:
msg não chega no chatwoot

#### Capturas de Tela/Vídeos:
LOG:
0|ApiEvolution  | [Evolution API]  v1.7.0  475399   -  Thu Mar 14 2024 01:56:27     LOG   [WAStartupService]  [object]
0|ApiEvolution  | {
0|ApiEvolution  |   local: 'WAStartupService.sendDataWebhook-global',
0|ApiEvolution  |   url: 'http://100.200.60.80:8087',
0|ApiEvolution  |   event: 'connection.update',
0|ApiEvolution  |   instance: 'plantao7',
0|ApiEvolution  |   data: { instance: 'plantao7', state: 'open', statusReason: 200 },
0|ApiEvolution  |   destination: 'http://100.200.60.80:8087/chatwoot/webhook/plantao7',
0|ApiEvolution  |   date_time: '2024-03-14T01:56:27.073Z',
0|ApiEvolution  |   sender: '551499655****@s.whatsapp.net',
0|ApiEvolution  |   server_url: 'http://100.200.60.80:8087',
0|ApiEvolution  |   apikey: 'B6D711FCDE4D4FD5936**********'
0|ApiEvolution  | }
0|ApiEvolution  | [Evolution API]  v1.7.0  475399   -  Thu Mar 14 2024 01:56:27     VERBOSE   [WAStartupService]  [string]  Getting remoteJid of instance
0|ApiEvolution  | [Evolution API]  v1.7.0  475399   -  Thu Mar 14 2024 01:56:27     ERROR   [WAStartupService]  [object]
0|ApiEvolution  | {
0|ApiEvolution  |   local: 'WAStartupService.sendDataWebhook-global',
0|ApiEvolution  |   message: 'Request failed with status code 404',
0|ApiEvolution  |   hostName: undefined,
0|ApiEvolution  |   syscall: undefined,
0|ApiEvolution  |   code: 'ERR_BAD_REQUEST',
0|ApiEvolution  |   error: undefined,
0|ApiEvolution  |   stack: 'AxiosError: Request failed with status code 404\n' +
0|ApiEvolution  |     '    at settle (/opt/evolution-api/node_modules/axios/dist/node/axios.cjs:1967:12)\n' +
0|ApiEvolution  |     '    at IncomingMessage.handleStreamEnd (/opt/evolution-api/node_modules/axios/dist/node/axios.cjs:3066:11)\n' +
0|ApiEvolution  |     '    at IncomingMessage.emit (node:events:525:35)\n' +
0|ApiEvolution  |     '    at IncomingMessage.emit (node:domain:489:12)\n' +
0|ApiEvolution  |     '    at endReadableNT (node:internal/streams/readable:1358:12)\n' +
0|ApiEvolution  |     '    at processTicksAndRejections (node:internal/process/task_queues:83:21)\n' +
0|ApiEvolution  |     '    at Axios.request (/opt/evolution-api/node_modules/axios/dist/node/axios.cjs:3877:41)\n' +
0|ApiEvolution  |     '    at runMicrotasks (<anonymous>)\n' +
0|ApiEvolution  |     '    at processTicksAndRejections (node:internal/process/task_queues:96:5)',
0|ApiEvolution  |   name: 'AxiosError',
0|ApiEvolution  |   url: 'http://100.200.60.80:8087',
0|ApiEvolution  |   server_url: 'http://100.200.60.80:8087'
0|ApiEvolution  | }
0|ApiEvolution  | [Evolution API]  v1.7.0  475399   -  Thu Mar 14 2024 03:12:54     VERBOSE   [WAStartupService]  [string]  Cleaned /opt/evolution-api/store/messages/plantao7/*.json

#### Ambiente:
- **Servidor:** [ex: DEBIAN  7]
- **Versão da API:** [ex: 1.7.0]

**Comment by leandrobtu** [comment]
Pessoal resolvi o problema aqui, na verdade o erro era não ter executado um passo na instalação do chatwoot, o passo de sincronizar o banco de dados:

docker compose run --rm rails bundle exec rails db:chatwoot_prepare

ao executar voltou a funcionar, vou fechar o ticket
