### ISSUE TITLE
[EN] Cannot read properties of undefined (reading 'id')[BUG]

### ISSUE THREAD

**Issue by bergpinheiro** [EvolutionAPI/evolution-api#585]
**Estou recebendo esse erro. Alguém sabe o que e?**

 stderr: 2,
  error: TypeError: Cannot read properties of undefined (reading 'id')
      at Object.sendMessageAck (/evolution/node_modules/baileys/lib/Socket/messages-recv.js:53:52)
      at BaileysStartupService.<anonymous> (/evolution/dist/src/api/services/channels/whatsapp.baileys.service.js:665:51)
      at Generator.next (<anonymous>)
      at fulfilled (/evolution/dist/src/api/services/channels/whatsapp.baileys.service.js:28:58)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
} 
[Evolution API]    v1.7.4  1   -  Tue May 07 2024 15:52:35     ERROR   [unhandledRejection]  [object]   
{
  origin: Promise {
    <rejected> TypeError: Cannot read properties of undefined (reading 'id')
        at Object.sendMessageAck (/evolution/node_modules/baileys/lib/Socket/messages-recv.js:53:52)
        at BaileysStartupService.<anonymous> (/evolution/dist/src/api/services/channels/whatsapp.baileys.service.js:665:51)
        at Generator.next (<anonymous>)
        at fulfilled (/evolution/dist/src/api/services/channels/whatsapp.baileys.service.js:28:58)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  },

  stderr: 2,
  error: TypeError: Cannot read properties of undefined (reading 'id')
      at Object.sendMessageAck (/evolution/node_modules/baileys/lib/Socket/messages-recv.js:53:52)
      at BaileysStartupService.<anonymous> (/evolution/dist/src/api/services/channels/whatsapp.baileys.service.js:665:51)
      at Generator.next (<anonymous>)
      at fulfilled (/evolution/dist/src/api/services/channels/whatsapp.baileys.service.js:28:58)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
} 
[Evolution API]    v1.7.4  1   -  Tue May 07 2024 15:52:35     ERROR   [unhandledRejection]  [object]   
{
  origin: Promise {
    <rejected> TypeError: Cannot read properties of undefined (reading 'id')
        at Object.sendMessageAck (/evolution/node_modules/baileys/lib/Socket/messages-recv.js:53:52)
        at BaileysStartupService.<anonymous> (/evolution/dist/src/api/services/channels/whatsapp.baileys.service.js:665:51)
        at Generator.next (<anonymous>)
        at fulfilled (/evolution/dist/src/api/services/channels/whatsapp.baileys.service.js:28:58)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  },

  stderr: 2,
  error: TypeError: Cannot read properties of undefined (reading 'id')
      at Object.sendMessageAck (/evolution/node_modules/baileys/lib/Socket/messages-recv.js:53:52)
      at BaileysStartupService.<anonymous> (/evolution/dist/src/api/services/channels/whatsapp.baileys.service.js:665:51)
      at Generator.next (<anonymous>)
      at fulfilled (/evolution/dist/src/api/services/channels/whatsapp.baileys.service.js:28:58)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
} 
[Evolution API]    v1.7.4  1   -  Tue May 07 2024 15:52:35     ERROR   [unhandledRejection]  [object]   
{
  origin: Promise {
    <rejected> TypeError: Cannot read properties of undefined (reading 'id')
        at Object.sendMessageAck (/evolution/node_modules/baileys/lib/Socket/messages-recv.js:53:52)
        at BaileysStartupService.<anonymous> (/evolution/dist/src/api/services/channels/whatsapp.baileys.service.js:665:51)
        at Generator.next (<anonymous>)
        at fulfilled (/evolution/dist/src/api/services/channels/whatsapp.baileys.service.js:28:58)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  },

  stderr: 2,
  error: TypeError: Cannot read properties of undefined (reading 'id')
      at Object.sendMessageAck (/evolution/node_modules/baileys/lib/Socket/messages-recv.js:53:52)
      at BaileysStartupService.<anonymous> (/evolution/dist/src/api/services/channels/whatsapp.baileys.service.js:665:51)
      at Generator.next (<anonymous>)
      at fulfilled (/evolution/dist/src/api/services/channels/whatsapp.baileys.service.js:28:58)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
} 
[Evolution API]    v1.7.4  1   -  Tue May 07 2024 15:52:35     ERROR   [unhandledRejection]  [object]   
{
  origin: Promise {
    <rejected> TypeError: Cannot read properties of undefined (reading 'id')
        at Object.sendMessageAck (/evolution/node_modules/baileys/lib/Socket/messages-recv.js:53:52)
        at BaileysStartupService.<anonymous> (/evolution/dist/src/api/services/channels/whatsapp.baileys.service.js:665:51)
        at Generator.next (<anonymous>)
        at fulfilled (/evolution/dist/src/api/services/channels/whatsapp.baileys.service.js:28:58)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  },

  stderr: 2,
  error: TypeError: Cannot read properties of undefined (reading 'id')
      at Object.sendMessageAck (/evolution/node_modules/baileys/lib/Socket/messages-recv.js:53:52)
      at BaileysStartupService.<anonymous> (/evolution/dist/src/api/services/channels/whatsapp.baileys.service.js:665:51)
      at Generator.next (<anonymous>)
      at fulfilled (/evolution/dist/src/api/services/channels/whatsapp.baileys.service.js:28:58)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
}

**Comment by DavidsonGomes** [comment]
Esse erro vem da Baileys, não é na evolution api
