### ISSUE TITLE
[EN][BUG] Number keeps getting logged out

### ISSUE THREAD

**Issue by kj2222** [EvolutionAPI/evolution-api#593]
#### Description:
Some of our numbers are getting logged out as soon as we scan: 

We tried to troubleshoot from Bailey's side

connection update {
connection: 'close',
lastDisconnect: {
error: Error: Stream Errored (restart required)
at WebSocketClient. (/Users/a/Documents/GitHub/Baileysfinal/src/Socket/socket.ts:662:7)
at WebSocketClient.emit (node:events:518:28)
at WebSocketClient.emit (node:domain:488:12)
at /Users/a/Documents/GitHub/Baileysfinal/src/Socket/socket.ts:338:23
at Object.decodeFrame (/Users/a/Documents/GitHub/Baileysfinal/src/Utils/noise-handler.ts:176:5)
at WebSocketClient.onMessageReceived (/Users/a/Documents/GitHub/Baileysfinal/src/Socket/socket.ts:310:9)
at WebSocketClient.emit (node:events:518:28)
at WebSocketClient.emit (node:domain:488:12)
at WebSocket. (/Users/a/Documents/GitHub/Baileysfinal/src/Socket/Client/web-socket-client.ts:40:52)
at WebSocket.emit (node:events:518:28) {
data: [Object],
isBoom: true,
isServer: true,
output: [Object]
},
date: 2024-05-11T19:52:34.215Z
}
}

**Comment by sidd82** [comment]
Same happening with me
