### ISSUE TITLE
Bug após deletar instância pelo maneger, Sumiu todas as que estavam desconectadas.

### ISSUE THREAD

**Issue by tizum** [EvolutionAPI/evolution-api#626]
### Welcome!

- [x] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

ao deletar uma instância que estava com status desconectada que foi criada a 3 dias atrás, que não houve nenhuma conexão realizada. 

O sistema faz a exclusão, porém todas as outras instancia que estavam desconectadas e que já haviam sido conectadas pelo menos 1 vez, sumiram todas de uma vez.... permanecendo somente as instancias conectadas.

### What did you expect?

deletar apenas a instancia que realizei a ação.

### What did you observe instead of what you expected?

deleta instancias desconectadas que não deveriam ser deletadas. pois deletei uma especifica e não todas que estavam desconectas.

### Which version of the API are you using?

versão homolog.

### What is your environment?

Docker

### Other environment specifications

Debian 12, 3CPU/4GB

### If applicable, paste the log output

[Evolution API]  [ma-lanatrs]  v1.8.0  1   -  Sat Jun 01 2024 00:16:08     INFO   [ChannelStartupService]  [string]  Baileys version: 2,2413,1 
     
[Evolution API]  [ma-lanatrs]  v1.8.0  1   -  Sat Jun 01 2024 00:19:38     INFO   [ChannelStartupService]  [string]  Baileys version: 2,2413,1 
     
[Evolution API]  [ma-lanatrs]  v1.8.0  1   -  Sat Jun 01 2024 00:23:08     INFO   [ChannelStartupService]  [string]  Baileys version: 2,2413,1 
[Evolution API]    v1.8.0  1   -  Sat Jun 01 2024 00:23:46     ERROR   [unhandledRejection]  [object]   
{
  origin: Promise {
    <rejected> MongoServerError: ns not found
        at Connection.onMessage (/evolution/node_modules/mongodb/lib/cmap/connection.js:231:30)
        at MessageStream.<anonymous> (/evolution/node_modules/mongodb/lib/cmap/connection.js:61:60)
        at MessageStream.emit (node:events:514:28)
        at processIncomingData (/evolution/node_modules/mongodb/lib/cmap/message_stream.js:125:16)
        at MessageStream._write (/evolution/node_modules/mongodb/lib/cmap/message_stream.js:33:9)
        at writeOrBuffer (node:internal/streams/writable:399:12)
        at _write (node:internal/streams/writable:340:10)
        at Writable.write (node:internal/streams/writable:344:10)
        at Socket.ondata (node:internal/streams/readable:785:22)
        at Socket.emit (node:events:514:28) {
      
      ok: 0,
      code: 26,
      codeName: 'NamespaceNotFound',
      [Symbol(errorLabels)]: Set(0) {}
    }
  },
      
  stderr: 2,
  error: MongoServerError: ns not found
      at Connection.onMessage (/evolution/node_modules/mongodb/lib/cmap/connection.js:231:30)
      at MessageStream.<anonymous> (/evolution/node_modules/mongodb/lib/cmap/connection.js:61:60)
      at MessageStream.emit (node:events:514:28)
      at processIncomingData (/evolution/node_modules/mongodb/lib/cmap/message_stream.js:125:16)
      at MessageStream._write (/evolution/node_modules/mongodb/lib/cmap/message_stream.js:33:9)
      at writeOrBuffer (node:internal/streams/writable:399:12)
      at _write (node:internal/streams/writable:340:10)
      at Writable.write (node:internal/streams/writable:344:10)
      at Socket.ondata (node:internal/streams/readable:785:22)
      at Socket.emit (node:events:514:28) {
    ok: 0,
    code: 26,
    codeName: 'NamespaceNotFound',
    [Symbol(errorLabels)]: Set(0) {}
  }
} 

### Additional Notes

Esse foi o log que estava no portainer, antes de realizar a ação, não havia problemas nenhum, estava com o portainer aberto quando realizei a exclusão, [ma-lanatrs] é exatamente a instancia que queria deletar apenas.

**Comment by cirinho** [comment]
já notei problema parecido na 1.7.5 e na 1.8.0 quando fui testar login com token das instâncias, basicamente uma instância desconectada sumiu do manager, daí eu recriei novamente a instância e reapareceu com as opções de configurações anterior, tipo webhook etc

**Comment by michaelvips** [comment]
Por padrão, instancias que não estão conectadas são deletadas depois de um tempo, se não quer esse comportamento deve usar volumes ou banco de dados e alterar essas opções no .Env

**Comment by tizum** [comment]
Eu adicionei a variável DEL_TEMP_INSTANCES=false na no Env, espero que não ocorra mais.
