### ISSUE TITLE
EVOLUTION 2.0 - Erro na criação de Webhook

### ISSUE THREAD

**Issue by tulergustavo** [EvolutionAPI/evolution-api#654]
### Bem-vido!

- [X] Sim, pesquisei problemas semelhantes no [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) e não encontrei nenhum.

### O que você fez?

Ao testar a Evolution em minha versão de testes de meu chatbot no n8n encontrei erro ao tentar configurar o webhook. A informação do webhook é até salva no meu banco de dados, porém, não funciona.

### O que você esperava?

Configurar o webhook para MESSAGES_UPSERT e receber as informações no n8n

### O que vc observou ao invés do que esperava?

Erro ao configurar/criar webhook, 

### Qual versão da API você está usando?

2.0

### Qual é o seu ambiente?

Windows

### Se aplicável, cole a saída do log

[Evolution API]    v2.0.0  128   -  Tue Jun 18 2024 11:47:41     ERROR   [unhandledRejection]  [object]   
{
  origin: Promise {
    <rejected> PrismaClientKnownRequestError: 
    Invalid `this.prismaRepository.webhook.create()` invocation in
    /evolution/dist/src/api/services/channel.service.js:191:49
    
      188 }
      189 setWebhook(data) {
      190     return __awaiter(this, void 0, void 0, function* () {
    → 191         yield this.prismaRepository.webhook.create(
    Unique constraint failed on the fields: (`instanceId`)
        at In.handleRequestError (/evolution/node_modules/@prisma/client/runtime/library.js:122:6877)
        at In.handleAndLogRequestError (/evolution/node_modules/@prisma/client/runtime/library.js:122:6211)
        at In.request (/evolution/node_modules/@prisma/client/runtime/library.js:122:5919)
        at async l (/evolution/node_modules/@prisma/client/runtime/library.js:127:11167) {
      code: 'P2002',
      clientVersion: '5.15.0',
      meta: [Object]
    }
  },
  stderr: 2,
  error: PrismaClientKnownRequestError: 
  Invalid `this.prismaRepository.webhook.create()` invocation in
  /evolution/dist/src/api/services/channel.service.js:191:49
  
    188 }
    189 setWebhook(data) {
    190     return __awaiter(this, void 0, void 0, function* () {
  → 191         yield this.prismaRepository.webhook.create(
  Unique constraint failed on the fields: (`instanceId`)
      at In.handleRequestError (/evolution/node_modules/@prisma/client/runtime/library.js:122:6877)
      at In.handleAndLogRequestError (/evolution/node_modules/@prisma/client/runtime/library.js:122:6211)
      at In.request (/evolution/node_modules/@prisma/client/runtime/library.js:122:5919)
      at async l (/evolution/node_modules/@prisma/client/runtime/library.js:127:11167) {
    code: 'P2002',
    clientVersion: '5.15.0',
    meta: { modelName: 'Webhook', target: [Array] }
  }
}

**Comment by guigagb** [comment]
É o mesmo problema do #655 ?

**Comment by dpaes** [comment]
Já tentou com uma versão mais atual do evolution? @tulergustavo

**Comment by bitarneto** [comment]
mesmo problema nao funciona
