### ISSUE TITLE
ERRO 429 - rate-overlimit

### ISSUE THREAD

**Issue by eduardochaves1** [EvolutionAPI/evolution-api#691]
### Bem-vido!

- [X] Sim, pesquisei problemas semelhantes no [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) e não encontrei nenhum.

### O que você fez?

De uns dias para cá comecei a receber constantemente o log da baileys sobre closing stale open sessions e de ontem para hoje comecei a receber uns logs de erro 429 da evo, dando a entender que uso da api estaria passando do limite. Alguém sabe explicar melhor que limite é este e como lidar com isto?

Vi aqui que esse caso aconteceu no endpoint de listar grupos em um número que tinha participação em 232 grupos que demorou 33s pra receber a resposta

Outra vez foi com envio de imagem onde uma automação acabou disparando 30 vezes no mesmo segundo

### O que você esperava?

Que houvesse explicitamente a definição de um limite de requisições por segundo por instância e/ou endpoint.

### O que vc observou ao invés do que esperava?

Que ao fazer algumas dezenas de requisições no mesmo momento para o mesmo endpoint a api dá erro de too many request.

### Qual versão da API você está usando?

1.8.1

### Qual é o seu ambiente?

Docker

### Outras expecificações do ambiente

Server: Ubuntu 20.04 LTS | 16GB RAM | 4 Cores

### Se aplicável, cole a saída do log

```
[Evolution API]  [wNKd1sAIGPqT]  v1.0.3  1   -  Fri Jul 12 2024 14:12:52     ERROR   [ChannelStartupService]  [object]   
Error: rate-overlimit
    at assertNodeErrorFree (/evolution-api/node_modules/@whiskeysockets/baileys/lib/WABinary/generic-utils.js:56:15)
    at query (/evolution-api/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:145:48)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.groupMetadata (/evolution-api/node_modules/@whiskeysockets/baileys/lib/Socket/groups.js:22:24) {
  data: 429,
  isBoom: true,
  isServer: true,
  output: {
    statusCode: 500,
    payload: {
      statusCode: 500,
      error: 'Internal Server Error',
      message: 'An internal server error occurred'
    },
    headers: {}
  }
} 

Closing stale open session for new outgoing prekey bundle
Closing session: SessionEntry {
  _chains: {
    'BUtfuCVFHNRB2Nmww4ru9I/yse+8eqB4m8o12O6i+Hwt': { chainKey: [Object], chainType: 1, messageKeys: {} }
  },
  registrationId: 1262739006,
  currentRatchet: {
    ephemeralKeyPair: {
      pubKey: <Buffer 05 4b 5f b8 25 45 1c d4 41 d8 d9 b0 c3 8a ee f4 8f f2 b1 ef bc 7a a0 78 9b ca 35 d8 ee a2 f8 7c 2d>,
      privKey: <Buffer 78 8b 90 37 a7 55 f3 b1 82 fb bc 8a 5b d8 99 e9 bd 0e 8c 44 d9 30 96 4c 7a f9 40 82 4d c6 32 4b>
    },
    lastRemoteEphemeralKey: <Buffer 05 59 c2 a4 24 ee a1 81 52 31 a4 f1 09 3b 1a 7b e4 c4 74 a0 ea 36 87 df fe 3d 45 27 60 16 19 25 77>,
    previousCounter: 0,
    rootKey: <Buffer 0b b7 da 42 28 e2 13 90 27 dc 95 f2 65 16 53 dc aa 80 29 d0 c1 00 f1 0d a8 6f 70 c1 77 02 52 69>
  },
  indexInfo: {
    baseKey: <Buffer 05 ed 9f 80 98 71 59 52 a3 34 eb e3 41 af 1a 58 e8 68 65 fc 2d 83 6b 74 a9 c4 7f b5 5c 16 79 a0 0a>,
    baseKeyType: 1,
    closed: -1,
    used: 1720381754698,
    created: 1720381754698,
    remoteIdentityKey: <Buffer 05 fb 2b c1 b6 17 b9 d6 40 f2 be 97 a5 32 8d b7 6e b1 06 66 9c 53 6d 14 6f b7 79 e4 65 f4 b0 76 69>
  },
  pendingPreKey: {
    signedKeyId: 3,
    baseKey: <Buffer 05 ed 9f 80 98 71 59 52 a3 34 eb e3 41 af 1a 58 e8 68 65 fc 2d 83 6b 74 a9 c4 7f b5 5c 16 79 a0 0a>,
    preKeyId: 2557
  }
}
Closing stale open session for new outgoing prekey bundle
Closing session: SessionEntry {
  _chains: {
    BRxucW0dUmn7pLSeU9UEn4QFe08gNTBsdh4zCuvYfxtp: { chainKey: [Object], chainType: 1, messageKeys: {} }
  },
  registrationId: 1262739006,
  currentRatchet: {
    ephemeralKeyPair: {
      pubKey: <Buffer 05 1c 6e 71 6d 1d 52 69 fb a4 b4 9e 53 d5 04 9f 84 05 7b 4f 20 35 30 6c 76 1e 33 0a eb d8 7f 1b 69>,
      privKey: <Buffer b0 93 9a 22 24 23 0a 75 b2 c1 46 29 b6 6f ae 2d ca 99 ee 8e fb ca 90 49 b6 fa 9d e2 8c 83 8a 41>
    },
    lastRemoteEphemeralKey: <Buffer 05 ec 03 47 48 8c 34 41 94 9f 4c be 02 b1 a6 8a f1 c0 85 de c9 36 de 8d 53 8a a5 51 01 88 a4 5a 6f>,
    previousCounter: 0,
    rootKey: <Buffer ef 69 57 3a d1 b5 ee f1 ae b7 0b 00 68 36 5d a4 7f 4e b1 80 4b ac e5 5e 1b f1 e8 41 8b ea 08 a2>
  },
  indexInfo: {
    baseKey: <Buffer 05 1e 9e 5a 91 49 e4 fa 72 b4 2b ed 25 50 fd ac fa b5 ac f8 bd ba dc 6e 1e cc 6d 7d 92 f6 d2 5a 57>,
    baseKeyType: 1,
    closed: -1,
    used: 1720804397776,
    created: 1720804397776,
    remoteIdentityKey: <Buffer 05 fb 2b c1 b6 17 b9 d6 40 f2 be 97 a5 32 8d b7 6e b1 06 66 9c 53 6d 14 6f b7 79 e4 65 f4 b0 76 69>
  },
  pendingPreKey: {
    signedKeyId: 4,
    baseKey: <Buffer 05 1e 9e 5a 91 49 e4 fa 72 b4 2b ed 25 50 fd ac fa b5 ac f8 bd ba dc 6e 1e cc 6d 7d 92 f6 d2 5a 57>
  }
}
```

### Notas Adicionais

Issue vinda desta thread no Discord: https://discord.com/channels/1127247206752206969/1212120862044590132/threads/1261364676139159706

**Comment by dpaes** [comment]
Estou fechando a issue pelo fato da versão mencionada não estar mais recebendo novas correções. Caso o problema persista em uma versão mais recente (v2), estaremos trabalhando para corrigir o quanto antes.

**Comment by GustavoGSA** [comment]
Também estou com esse problema, alguém conseguiu resolver?

**Comment by luispimenta** [comment]
@eduardochaves1 @GustavoGSA conseguiram resolver essa questão?

**Comment by GustavoGSA** [comment]
> @eduardochaves1 @GustavoGSA conseguiram resolver essa questão?

Rapaz eu nem vi mais isso, criei minha própria API, evolution da não é pau pra todo lado
