### ISSUE TITLE
[INIT] crypto.randomUUID is not a function

### ISSUE THREAD

**Issue by alexmdcampo** [EvolutionAPI/evolution-api#740]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

Usando a versão atendai/evolution-api:v2.0.7-rc

Ao configurar a v2 com postgres e redis , nos logs informa que esta migrado e tudo pronto porem exibe o erro abaixo no /manager

Unexpected Application Error!
crypto.randomUUID is not a function
TypeError: crypto.randomUUID is not a function
    at Iz (http://192.168.1.200:9090/assets/index-TzTbeCvz.js:303:153267)
    at Ev (http://192.168.1.200:9090/assets/index-TzTbeCvz.js:38:16998)
    at _j (http://192.168.1.200:9090/assets/index-TzTbeCvz.js:40:44030)
    at Sj (http://192.168.1.200:9090/assets/index-TzTbeCvz.js:40:39766)
    at CI (http://192.168.1.200:9090/assets/index-TzTbeCvz.js:40:39694)
    at Zd (http://192.168.1.200:9090/assets/index-TzTbeCvz.js:40:39547)
    at Xg (http://192.168.1.200:9090/assets/index-TzTbeCvz.js:40:35914)
    at xj (http://192.168.1.200:9090/assets/index-TzTbeCvz.js:40:34865)
    at j (http://192.168.1.200:9090/assets/index-TzTbeCvz.js:25:1582)
    at MessagePort.I (http://192.168.1.200:9090/assets/index-TzTbeCvz.js:25:1946)

### What did you expect?

/manager não abre

### What did you observe instead of what you expected?

.

### Screenshots/Videos

![image](https://github.com/user-attachments/assets/4abed83e-78db-458a-be38-8a9dcb2746d6)

### Which version of the API are you using?

evolution-api:v2.0.7-rc

### What is your environment?

Windows

### Other environment specifications

i5core ARM
Ubuntu 22

**Comment by RonaldoAlencar** [comment]
Amigo, boa noite, tive o mesmo problema que você. Resolvi acessando a rota do manager com o SSL https://

**Comment by matheusdamiao** [comment]
Estou tendo o mesmo erro aqui. Acessar com SSL não resolveu, nem carregou.

**Comment by dpaes** [comment]
@alexmdcampo saberia me dizer se o erro persiste usando uma versão mais atual da v2 do evolution?
