### ISSUE TITLE
Erro ao cadastrar Proxy (mostra sucesso, mas não funciona)

### ISSUE THREAD

**Issue by vidz1979** [EvolutionAPI/evolution-api#766]
### Bem-vido!

- [X] Sim, pesquisei problemas semelhantes no [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) e não encontrei nenhum.

### O que você fez?

Entrei no Manager, selecionei uma instancia e tentei adicionar um Proxy a ela.

### O que você esperava?

Que o proxy fosse cadastrado

### O que vc observou ao invés do que esperava?

Mensagem de sucesso, porém proxy não foi adicionado e consta erro no log.

### Capturas de Tela/Vídeos

![image](https://github.com/user-attachments/assets/68d25544-313a-42f5-ab83-fd0c7122ad57)

### Qual versão da API você está usando?

2.0.9-rc

### Qual é o seu ambiente?

Linux

### Se aplicável, cole a saída do log

```
{
  origin: Promise {
    <rejected> PrismaClientKnownRequestError: 
    Invalid `this.prismaRepository.proxy.create()` invocation in
    /evolution/dist/src/api/services/channel.service.js:549:47
    
      546 }
      547 setProxy(data) {
      548     return __awaiter(this, void 0, void 0, function* () {
    → 549         yield this.prismaRepository.proxy.create(
    Unique constraint failed on the fields: (`instanceId`)
        at _n.handleRequestError (/evolution/node_modules/@prisma/client/runtime/library.js:121:7749)
        at _n.handleAndLogRequestError (/evolution/node_modules/@prisma/client/runtime/library.js:121:7057)
        at _n.request (/evolution/node_modules/@prisma/client/runtime/library.js:121:6741)
        at async l (/evolution/node_modules/@prisma/client/runtime/library.js:130:9355) {
      code: 'P2002',
      clientVersion: '5.18.0',
      meta: [Object]
    }
  },

  stderr: 2,
  error: PrismaClientKnownRequestError: 
  Invalid `this.prismaRepository.proxy.create()` invocation in
  /evolution/dist/src/api/services/channel.service.js:549:47
  

}
    547 setProxy(data) {
    548     return __awaiter(this, void 0, void 0, function* () {
  → 549         yield this.prismaRepository.proxy.create(
  Unique constraint failed on the fields: (`instanceId`)
      at _n.handleRequestError (/evolution/node_modules/@prisma/client/runtime/library.js:121:7749)
      at _n.handleAndLogRequestError (/evolution/node_modules/@prisma/client/runtime/library.js:121:7057)
      at _n.request (/evolution/node_modules/@prisma/client/runtime/library.js:121:6741)
      at async l (/evolution/node_modules/@prisma/client/runtime/library.js:130:9355) {
    code: 'P2002',
    clientVersion: '5.18.0',
    meta: { modelName: 'Proxy', target: [Array] }
  }
} 
```

**Comment by dpaes** [comment]
Poderia informar se ainda está com o problema? em caso da resposta ser sim, chegou a testar em outra versão do evolution como a 2.1.2?

**Comment by MichaelRodriguesOficial** [comment]
O erro ainda persiste ?
Estou usando a 2.2.3 e pra mim apareceu o mesmo erro!
