### ISSUE TITLE
TypeError erro mensagens 2.0.9-rc

### ISSUE THREAD

**Issue by marioalexandreantunes** [EvolutionAPI/evolution-api#785]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

Evolution ao tentar iniciar Typebot não funciona.

### What did you expect?

que a mensagem chega-se ao Typebot

### What did you observe instead of what you expected?

Em vez que verificar bot atraves do typebot, a API passou para OpenAI e Dify (e ambos estão desactivados).

### Which version of the API are you using?

2.0.9.-rc

### What is your environment?

Linux

### Other environment specifications

VPS 
4 vCPU Cores
6 GB RAM
1 Snapshot
100 GB NVMe
Ubuntu 22.04

### If applicable, paste the log output

```
[Evolution API]    v2.0.9-rc  126   -  Fri Aug 16 2024 10:08:09     LOG   [TypebotService]  [string]  Debounce complete. Processing message: Ola tudo bem? preciso da tua ajuda 
Erro ao processar mensagens: TypeError: messages is not iterable
    at /evolution/dist/src/api/integrations/typebot/services/typebot.service.js:1010:43
    at Generator.next (<anonymous>)
    at /evolution/dist/src/api/integrations/typebot/services/typebot.service.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/evolution/dist/src/api/integrations/typebot/services/typebot.service.js:4:12)
    at processMessages (/evolution/dist/src/api/integrations/typebot/services/typebot.service.js:1009:24)
    at TypebotService.<anonymous> (/evolution/dist/src/api/integrations/typebot/services/typebot.service.js:947:13)
    at Generator.next (<anonymous>)
    at /evolution/dist/src/api/integrations/typebot/services/typebot.service.js:8:71
    at new Promise (<anonymous>)
[Evolution API]    v2.0.9-rc  126   -  Fri Aug 16 2024 10:08:09     ERROR   [unhandledRejection]  [object]   
{
  origin: Promise {
    <rejected> TypeError: Cannot read properties of undefined (reading 'length')
        at TypebotService.<anonymous> (/evolution/dist/src/api/integrations/typebot/services/typebot.service.js:1510:35)
        at Generator.next (<anonymous>)
        at fulfilled (/evolution/dist/src/api/integrations/typebot/services/typebot.service.js:5:58)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  },
      
  stderr: 2,
  error: TypeError: Cannot read properties of undefined (reading 'length')
      at TypebotService.<anonymous> (/evolution/dist/src/api/integrations/typebot/services/typebot.service.js:1510:35)
      at Generator.next (<anonymous>)
      at fulfilled (/evolution/dist/src/api/integrations/typebot/services/typebot.service.js:5:58)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
} 
```

**Comment by marioalexandreantunes** [comment]
Pode fechar , erro meu com a url e nome do typebot

**Comment by dpaes** [comment]
so colocar closed aki embaixo \/
