### ISSUE TITLE
CACHE_REDIS_ENABLED não é respeitado

### ISSUE THREAD

**Issue by dev-luizf** [EvolutionAPI/evolution-api#799]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

Fiz uma instalação da evolution clonando o repositório e conectei uma instância utilizando as seguintes variáveis para o redis:

CACHE_REDIS_ENABLED=false
CACHE_REDIS_URI=redis://localhost:6379/6
CACHE_REDIS_PREFIX_KEY=evolution
CACHE_REDIS_SAVE_INSTANCES=false
CACHE_LOCAL_ENABLED=false

### What did you expect?

Esperava que o cache não fosse utilizado quando a variável CACHE_REDIS_ENABLED for igual a false

### What did you observe instead of what you expected?

A api tenta utilizar o redis

### Which version of the API are you using?

2.0

### What is your environment?

Linux

### If applicable, paste the log output

[Evolution API]    v2.1.0  370280   -  Tue Aug 20 2024 16:58:34     ERROR   [CacheService]  [object]   
TypeError: Cannot read properties of undefined (reading 'hGet')
    at CacheService.hGet (/home/luiz/Documentos/evolution-api/src/api/services/cache.service.ts:25:37)
    at readData (/home/luiz/Documentos/evolution-api/src/utils/use-multi-file-auth-state-prisma.ts:105:28)
    at /home/luiz/Documentos/evolution-api/src/utils/use-multi-file-auth-state-prisma.ts:146:33
    at Array.map (<anonymous>)
    at Object.get (/home/luiz/Documentos/evolution-api/src/utils/use-multi-file-auth-state-prisma.ts:145:17)
    at Object.get (/home/luiz/Documentos/evolution-api/node_modules/baileys/lib/Utils/auth-utils.js:43:45)
    at Object.get (/home/luiz/Documentos/evolution-api/node_modules/baileys/lib/Utils/auth-utils.js:97:48)
    at /home/luiz/Documentos/evolution-api/node_modules/baileys/lib/Socket/chats.js:348:57
    at Object.transaction (/home/luiz/Documentos/evolution-api/node_modules/baileys/lib/Utils/auth-utils.js:136:32)
    at /home/luiz/Documentos/evolution-api/node_modules/baileys/lib/Socket/chats.js:336:30 

[Evolution API]    v2.1.0  370280   -  Tue Aug 20 2024 16:58:34     ERROR   [CacheService]  [object]   
TypeError: Cannot read properties of undefined (reading 'hGet')
    at CacheService.hGet (/home/luiz/Documentos/evolution-api/src/api/services/cache.service.ts:25:37)
    at readData (/home/luiz/Documentos/evolution-api/src/utils/use-multi-file-auth-state-prisma.ts:105:28)
    at /home/luiz/Documentos/evolution-api/src/utils/use-multi-file-auth-state-prisma.ts:146:33
    at Array.map (<anonymous>)
    at Object.get (/home/luiz/Documentos/evolution-api/src/utils/use-multi-file-auth-state-prisma.ts:145:17)
    at Object.get (/home/luiz/Documentos/evolution-api/node_modules/baileys/lib/Utils/auth-utils.js:43:45)
    at Object.get (/home/luiz/Documentos/evolution-api/node_modules/baileys/lib/Utils/auth-utils.js:97:48)
    at /home/luiz/Documentos/evolution-api/node_modules/baileys/lib/Socket/chats.js:348:57
    at Object.transaction (/home/luiz/Documentos/evolution-api/node_modules/baileys/lib/Utils/auth-utils.js:136:26)
    at /home/luiz/Documentos/evolution-api/node_modules/baileys/lib/Socket/chats.js:336:9 

[Evolution API]    v2.1.0  370280   -  Tue Aug 20 2024 16:58:34     ERROR   [CacheService]  [object]   
TypeError: Cannot read properties of undefined (reading 'hGet')
    at CacheService.hGet (/home/luiz/Documentos/evolution-api/src/api/services/cache.service.ts:25:37)
    at readData (/home/luiz/Documentos/evolution-api/src/utils/use-multi-file-auth-state-prisma.ts:105:28)
    at /home/luiz/Documentos/evolution-api/src/utils/use-multi-file-auth-state-prisma.ts:146:33
    at Array.map (<anonymous>)
    at Object.get (/home/luiz/Documentos/evolution-api/src/utils/use-multi-file-auth-state-prisma.ts:145:17)
    at Object.get (/home/luiz/Documentos/evolution-api/node_modules/baileys/lib/Utils/auth-utils.js:43:45)
    at Object.get (/home/luiz/Documentos/evolution-api/node_modules/baileys/lib/Utils/auth-utils.js:97:48)
    at /home/luiz/Documentos/evolution-api/node_modules/baileys/lib/Socket/chats.js:348:57
    at Object.transaction (/home/luiz/Documentos/evolution-api/node_modules/baileys/lib/Utils/auth-utils.js:136:26)
    at /home/luiz/Documentos/evolution-api/node_modules/baileys/lib/Socket/chats.js:336:9 

[Evolution API]    v2.1.0  370280   -  Tue Aug 20 2024 16:58:34     ERROR   [CacheService]  [object]   
TypeError: Cannot read properties of undefined (reading 'hGet')
    at CacheService.hGet (/home/luiz/Documentos/evolution-api/src/api/services/cache.service.ts:25:37)
    at readData (/home/luiz/Documentos/evolution-api/src/utils/use-multi-file-auth-state-prisma.ts:105:28)
    at /home/luiz/Documentos/evolution-api/src/utils/use-multi-file-auth-state-prisma.ts:146:33
    at Array.map (<anonymous>)
    at Object.get (/home/luiz/Documentos/evolution-api/src/utils/use-multi-file-auth-state-prisma.ts:145:17)
    at Object.get (/home/luiz/Documentos/evolution-api/node_modules/baileys/lib/Utils/auth-utils.js:43:45)
    at Object.get (/home/luiz/Documentos/evolution-api/node_modules/baileys/lib/Utils/auth-utils.js:97:48)
    at /home/luiz/Documentos/evolution-api/node_modules/baileys/lib/Socket/chats.js:348:57
    at Object.transaction (/home/luiz/Documentos/evolution-api/node_modules/baileys/lib/Utils/auth-utils.js:136:26)
    at /home/luiz/Documentos/evolution-api/node_modules/baileys/lib/Socket/chats.js:336:9 

[Evolution API]    v2.1.0  370280   -  Tue Aug 20 2024 16:58:34     ERROR   [CacheService]  [object]   
TypeError: Cannot read properties of undefined (reading 'hGet')
    at CacheService.hGet (/home/luiz/Documentos/evolution-api/src/api/services/cache.service.ts:25:37)
    at readData (/home/luiz/Documentos/evolution-api/src/utils/use-multi-file-auth-state-prisma.ts:105:28)
    at /home/luiz/Documentos/evolution-api/src/utils/use-multi-file-auth-state-prisma.ts:146:33
    at Array.map (<anonymous>)
    at Object.get (/home/luiz/Documentos/evolution-api/src/utils/use-multi-file-auth-state-prisma.ts:145:17)
    at Object.get (/home/luiz/Documentos/evolution-api/node_modules/baileys/lib/Utils/auth-utils.js:43:45)
    at Object.get (/home/luiz/Documentos/evolution-api/node_modules/baileys/lib/Utils/auth-utils.js:97:48)
    at /home/luiz/Documentos/evolution-api/node_modules/baileys/lib/Socket/chats.js:348:57
    at Object.transaction (/home/luiz/Documentos/evolution-api/node_modules/baileys/lib/Utils/auth-utils.js:136:26)
    at /home/luiz/Documentos/evolution-api/node_modules/baileys/lib/Socket/chats.js:336:9 

[Evolution API]    v2.1.0  370280   -  Tue Aug 20 2024 16:58:35     ERROR   [CacheService]  [object]   
TypeError: Cannot read properties of undefined (reading 'hSet')
    at CacheService.hSet (/home/luiz/Documentos/evolution-api/src/api/services/cache.service.ts:49:24)
    at writeData (/home/luiz/Documentos/evolution-api/src/utils/use-multi-file-auth-state-prisma.ts:92:26)
    at Object.set (/home/luiz/Documentos/evolution-api/src/utils/use-multi-file-auth-state-prisma.ts:163:34)
    at Object.set (/home/luiz/Documentos/evolution-api/node_modules/baileys/lib/Utils/auth-utils.js:63:25)
    at Object.transaction (/home/luiz/Documentos/evolution-api/node_modules/baileys/lib/Utils/auth-utils.js:147:45)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at /home/luiz/Documentos/evolution-api/node_modules/baileys/lib/Socket/chats.js:336:9
    at /home/luiz/Documentos/evolution-api/node_modules/baileys/lib/Utils/event-buffer.js:105:36
    at doAppStateSync (/home/luiz/Documentos/evolution-api/node_modules/baileys/lib/Socket/chats.js:752:17)
    at /home/luiz/Documentos/evolution-api/node_modules/baileys/lib/Socket/chats.js:731:21 

[Evolution API]    v2.1.0  370280   -  Tue Aug 20 2024 16:58:35     ERROR   [CacheService]  [object]   
TypeError: Cannot read properties of undefined (reading 'hSet')
    at CacheService.hSet (/home/luiz/Documentos/evolution-api/src/api/services/cache.service.ts:49:24)
    at writeData (/home/luiz/Documentos/evolution-api/src/utils/use-multi-file-auth-state-prisma.ts:92:26)
    at Object.set (/home/luiz/Documentos/evolution-api/src/utils/use-multi-file-auth-state-prisma.ts:163:34)
    at Object.set (/home/luiz/Documentos/evolution-api/node_modules/baileys/lib/Utils/auth-utils.js:63:25)
    at Object.transaction (/home/luiz/Documentos/evolution-api/node_modules/baileys/lib/Utils/auth-utils.js:147:45)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at /home/luiz/Documentos/evolution-api/node_modules/baileys/lib/Socket/chats.js:336:9
    at /home/luiz/Documentos/evolution-api/node_modules/baileys/lib/Utils/event-buffer.js:105:36
    at doAppStateSync (/home/luiz/Documentos/evolution-api/node_modules/baileys/lib/Socket/chats.js:752:17)
    at /home/luiz/Documentos/evolution-api/node_modules/baileys/lib/Socket/chats.js:731:21 

[Evolution API]    v2.1.0  370280   -  Tue Aug 20 2024 16:58:35     ERROR   [CacheService]  [object]   
TypeError: Cannot read properties of undefined (reading 'hSet')
    at CacheService.hSet (/home/luiz/Documentos/evolution-api/src/api/services/cache.service.ts:49:24)
    at writeData (/home/luiz/Documentos/evolution-api/src/utils/use-multi-file-auth-state-prisma.ts:92:26)
    at Object.set (/home/luiz/Documentos/evolution-api/src/utils/use-multi-file-auth-state-prisma.ts:163:34)
    at Object.set (/home/luiz/Documentos/evolution-api/node_modules/baileys/lib/Utils/auth-utils.js:63:25)
    at Object.transaction (/home/luiz/Documentos/evolution-api/node_modules/baileys/lib/Utils/auth-utils.js:147:45)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at /home/luiz/Documentos/evolution-api/node_modules/baileys/lib/Socket/chats.js:336:9
    at /home/luiz/Documentos/evolution-api/node_modules/baileys/lib/Utils/event-buffer.js:105:36
    at doAppStateSync (/home/luiz/Documentos/evolution-api/node_modules/baileys/lib/Socket/chats.js:752:17)
    at /home/luiz/Documentos/evolution-api/node_modules/baileys/lib/Socket/chats.js:731:21 

[Evolution API]    v2.1.0  370280   -  Tue Aug 20 2024 16:58:35     ERROR   [CacheService]  [object]   
TypeError: Cannot read properties of undefined (reading 'hSet')
    at CacheService.hSet (/home/luiz/Documentos/evolution-api/src/api/services/cache.service.ts:49:24)
    at writeData (/home/luiz/Documentos/evolution-api/src/utils/use-multi-file-auth-state-prisma.ts:92:26)
    at Object.set (/home/luiz/Documentos/evolution-api/src/utils/use-multi-file-auth-state-prisma.ts:163:34)
    at Object.set (/home/luiz/Documentos/evolution-api/node_modules/baileys/lib/Utils/auth-utils.js:63:25)
    at Object.transaction (/home/luiz/Documentos/evolution-api/node_modules/baileys/lib/Utils/auth-utils.js:147:45)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at /home/luiz/Documentos/evolution-api/node_modules/baileys/lib/Socket/chats.js:336:9
    at /home/luiz/Documentos/evolution-api/node_modules/baileys/lib/Utils/event-buffer.js:105:36
    at doAppStateSync (/home/luiz/Documentos/evolution-api/node_modules/baileys/lib/Socket/chats.js:752:17)
    at /home/luiz/Documentos/evolution-api/node_modules/baileys/lib/Socket/chats.js:731:21 

[Evolution API]    v2.1.0  370280   -  Tue Aug 20 2024 16:58:35     ERROR   [CacheService]  [object]   
TypeError: Cannot read properties of undefined (reading 'hDelete')
    at CacheService.hDelete (/home/luiz/Documentos/evolution-api/src/api/services/cache.service.ts:71:24)
    at removeData (/home/luiz/Documentos/evolution-api/src/utils/use-multi-file-auth-state-prisma.ts:122:28)
    at Object.set (/home/luiz/Documentos/evolution-api/src/utils/use-multi-file-auth-state-prisma.ts:163:58)
    at Object.set (/home/luiz/Documentos/evolution-api/node_modules/baileys/lib/Utils/auth-utils.js:63:25)
    at Object.transaction (/home/luiz/Documentos/evolution-api/node_modules/baileys/lib/Utils/auth-utils.js:147:45)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at /home/luiz/Documentos/evolution-api/node_modules/baileys/lib/Socket/chats.js:336:9
    at /home/luiz/Documentos/evolution-api/node_modules/baileys/lib/Utils/event-buffer.js:105:36
    at doAppStateSync (/home/luiz/Documentos/evolution-api/node_modules/baileys/lib/Socket/chats.js:752:17)
    at /home/luiz/Documentos/evolution-api/node_modules/baileys/lib/Socket/chats.js:731:21 

[Evolution API]    v2.1.0  370280   -  Tue Aug 20 2024 16:58:35     ERROR   [CacheService]  [object]   
TypeError: Cannot read properties of undefined (reading 'hSet')
    at CacheService.hSet (/home/luiz/Documentos/evolution-api/src/api/services/cache.service.ts:49:24)
    at writeData (/home/luiz/Documentos/evolution-api/src/utils/use-multi-file-auth-state-prisma.ts:92:26)
    at Object.set (/home/luiz/Documentos/evolution-api/src/utils/use-multi-file-auth-state-prisma.ts:163:34)
    at Object.set (/home/luiz/Documentos/evolution-api/node_modules/baileys/lib/Utils/auth-utils.js:63:25)
    at Object.set (/home/luiz/Documentos/evolution-api/node_modules/baileys/lib/Utils/auth-utils.js:125:30)
    at Object.storeSession (/home/luiz/Documentos/evolution-api/node_modules/baileys/lib/Signal/libsignal.js:111:24)
    at SessionCipher.storeRecord (/home/luiz/Documentos/evolution-api/node_modules/libsignal/src/session_cipher.js:58:28)
    at Object.558981316063.0 [as awaitable] (/home/luiz/Documentos/evolution-api/node_modules/libsignal/src/session_cipher.js:208:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at _asyncQueueExecutor (/home/luiz/Documentos/evolution-api/node_modules/libsignal/src/queue_job.js:20:29) 

[Evolution API]    v2.1.0  370280   -  Tue Aug 20 2024 16:58:36     ERROR   [CacheService]  [object]   
TypeError: Cannot read properties of undefined (reading 'hDelete')
    at CacheService.hDelete (/home/luiz/Documentos/evolution-api/src/api/services/cache.service.ts:71:24)
    at removeData (/home/luiz/Documentos/evolution-api/src/utils/use-multi-file-auth-state-prisma.ts:122:28)
    at Object.set (/home/luiz/Documentos/evolution-api/src/utils/use-multi-file-auth-state-prisma.ts:163:58)
    at Object.set (/home/luiz/Documentos/evolution-api/node_modules/baileys/lib/Utils/auth-utils.js:63:25)
    at Object.transaction (/home/luiz/Documentos/evolution-api/node_modules/baileys/lib/Utils/auth-utils.js:147:45)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at /home/luiz/Documentos/evolution-api/node_modules/baileys/lib/Socket/chats.js:336:9
    at /home/luiz/Documentos/evolution-api/node_modules/baileys/lib/Utils/event-buffer.js:105:36
    at processNotification (/home/luiz/Documentos/evolution-api/node_modules/baileys/lib/Socket/messages-recv.js:300:21)
    at /home/luiz/Documentos/evolution-api/node_modules/baileys/lib/Socket/messages-recv.js:557:29 

[Evolution API]    v2.1.0  370280   -  Tue Aug 20 2024 16:58:36     ERROR   [CacheService]  [object]   
TypeError: Cannot read properties of undefined (reading 'hSet')
    at CacheService.hSet (/home/luiz/Documentos/evolution-api/src/api/services/cache.service.ts:49:24)
    at writeData (/home/luiz/Documentos/evolution-api/src/utils/use-multi-file-auth-state-prisma.ts:92:26)
    at Object.set (/home/luiz/Documentos/evolution-api/src/utils/use-multi-file-auth-state-prisma.ts:163:34)
    at Object.set (/home/luiz/Documentos/evolution-api/node_modules/baileys/lib/Utils/auth-utils.js:63:25)
    at Object.set (/home/luiz/Documentos/evolution-api/node_modules/baileys/lib/Utils/auth-utils.js:125:30)
    at Object.storeSession (/home/luiz/Documentos/evolution-api/node_modules/baileys/lib/Signal/libsignal.js:111:24)
    at SessionCipher.storeRecord (/home/luiz/Documentos/evolution-api/node_modules/libsignal/src/session_cipher.js:58:28)
    at Object.558981316063.0 [as awaitable] (/home/luiz/Documentos/evolution-api/node_modules/libsignal/src/session_cipher.js:208:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at _asyncQueueExecutor (/home/luiz/Documentos/evolution-api/node_modules/libsignal/src/queue_job.js:20:29) 

[Evolution API]    v2.1.0  370280   -  Tue Aug 20 2024 16:58:36     ERROR   [CacheService]  [object]   
TypeError: Cannot read properties of undefined (reading 'hSet')
    at CacheService.hSet (/home/luiz/Documentos/evolution-api/src/api/services/cache.service.ts:49:24)
    at writeData (/home/luiz/Documentos/evolution-api/src/utils/use-multi-file-auth-state-prisma.ts:92:26)
    at Object.set (/home/luiz/Documentos/evolution-api/src/utils/use-multi-file-auth-state-prisma.ts:163:34)
    at Object.set (/home/luiz/Documentos/evolution-api/node_modules/baileys/lib/Utils/auth-utils.js:63:25)
    at Object.set (/home/luiz/Documentos/evolution-api/node_modules/baileys/lib/Utils/auth-utils.js:125:30)
    at Object.storeSession (/home/luiz/Documentos/evolution-api/node_modules/baileys/lib/Signal/libsignal.js:111:24)
    at SessionCipher.storeRecord (/home/luiz/Documentos/evolution-api/node_modules/libsignal/src/session_cipher.js:58:28)
    at Object.558981316063.0 [as awaitable] (/home/luiz/Documentos/evolution-api/node_modules/libsignal/src/session_cipher.js:208:24)
    at _asyncQueueExecutor (/home/luiz/Documentos/evolution-api/node_modules/libsignal/src/queue_job.js:20:29) 

recv 295 chats, 700 contacts, 403 msgs (is latest: true, progress: undefined%), type: undefined
[Evolution API]  [test]  v2.1.0  370280   -  Tue Aug 20 2024 16:58:36     ERROR   [ChannelStartupService]  [string]  line 817 
[Evolution API]  [test]  v2.1.0  370280   -  Tue Aug 20 2024 16:58:36     ERROR   [ChannelStartupService]  [string]  Error: Cannot read properties of null (reading 'has') 
[Evolution API]    v2.1.0  370280   -  Tue Aug 20 2024 16:58:40     ERROR   [CacheService]  [object]   
TypeError: Cannot read properties of undefined (reading 'hSet')
    at CacheService.hSet (/home/luiz/Documentos/evolution-api/src/api/services/cache.service.ts:49:24)
    at writeData (/home/luiz/Documentos/evolution-api/src/utils/use-multi-file-auth-state-prisma.ts:92:26)
    at Object.set (/home/luiz/Documentos/evolution-api/src/utils/use-multi-file-auth-state-prisma.ts:163:34)
    at Object.set (/home/luiz/Documentos/evolution-api/node_modules/baileys/lib/Utils/auth-utils.js:63:25)
    at Object.set (/home/luiz/Documentos/evolution-api/node_modules/baileys/lib/Utils/auth-utils.js:125:30)
    at Object.storeSession (/home/luiz/Documentos/evolution-api/node_modules/baileys/lib/Signal/libsignal.js:111:24)
    at SessionCipher.storeRecord (/home/luiz/Documentos/evolution-api/node_modules/libsignal/src/session_cipher.js:58:28)
    at Object.558981316063.0 [as awaitable] (/home/luiz/Documentos/evolution-api/node_modules/libsignal/src/session_cipher.js:208:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at _asyncQueueExecutor (/home/luiz/Documentos/evolution-api/node_modules/libsignal/src/queue_job.js:20:29) 

[Evolution API]    v2.1.0  370280   -  Tue Aug 20 2024 16:58:40     ERROR   [CacheService]  [object]   
TypeError: Cannot read properties of undefined (reading 'hSet')
    at CacheService.hSet (/home/luiz/Documentos/evolution-api/src/api/services/cache.service.ts:49:24)
    at writeData (/home/luiz/Documentos/evolution-api/src/utils/use-multi-file-auth-state-prisma.ts:92:26)
    at Object.set (/home/luiz/Documentos/evolution-api/src/utils/use-multi-file-auth-state-prisma.ts:163:34)
    at Object.set (/home/luiz/Documentos/evolution-api/node_modules/baileys/lib/Utils/auth-utils.js:63:25)
    at Object.set (/home/luiz/Documentos/evolution-api/node_modules/baileys/lib/Utils/auth-utils.js:125:30)
    at Object.storeSession (/home/luiz/Documentos/evolution-api/node_modules/baileys/lib/Signal/libsignal.js:111:24)
    at SessionCipher.storeRecord (/home/luiz/Documentos/evolution-api/node_modules/libsignal/src/session_cipher.js:58:28)
    at Object.558981316063.0 [as awaitable] (/home/luiz/Documentos/evolution-api/node_modules/libsignal/src/session_cipher.js:208:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at _asyncQueueExecutor (/home/luiz/Documentos/evolution-api/node_modules/libsignal/src/queue_job.js:20:29) 

recv 170 chats, 161 contacts, 5097 msgs (is latest: false, progress: undefined%), type: undefined
[Evolution API]  [test]  v2.1.0  370280   -  Tue Aug 20 2024 16:58:41     ERROR   [ChannelStartupService]  [string]  line 817 
[Evolution API]  [test]  v2.1.0  370280   -  Tue Aug 20 2024 16:58:41     ERROR   [ChannelStartupService]  [string]  Error: Cannot read properties of null (reading 'has') 
[Evolution API]  [test]  v2.1.0  370280   -  Tue Aug 20 2024 16:59:36     ERROR   [ChannelStartupService]  [string]  line 817 
[Evolution API]  [test]  v2.1.0  370280   -  Tue Aug 20 2024 16:59:36     ERROR   [ChannelStartupService]  [string]  Error: Cannot read properties of null (reading 'has') 

### Additional Notes

Para deixar claro, eu tenho o redis rodando no docker, porém gostaria de usar não usá-lo, visto que o meu caso de uso é bem simples e eu quero economizar recursos.

**Comment by sosnoski** [comment]
olá. tente setar `true` em `CACHE_LOCAL_ENABLED=false`.

Apenas um palpite. Avise aqui se der certo. Abs

**Comment by dev-luizf** [comment]
> olá. tente setar `true` em `CACHE_LOCAL_ENABLED=false`.
> 
> Apenas um palpite. Avise aqui se der certo. Abs

Não funciona, já testei. Parece que o redis e o postgres agora são obrigatórios, o que pra mim não é muito interessante, visto que só quero usar a api pra disparar webhook quando receber mensagem e responder usando sendText. Acho que vou usar a v1.

**Comment by dpaes** [comment]
Sim, o postgres e redis são obrigatórios. Pois o redis faz algumas operações em que insere dados com TTL -1, logo precisa desse serviço disponível.
