### ISSUE TITLE
SQS Não Funciona

### ISSUE THREAD

**Issue by umcliquedigital** [EvolutionAPI/evolution-api#855]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

Conectei o SQS da Amazon no Env e ativei ele através do manager do Post.
Quando eu faço o Get, ele confirma que o SQS está ativado.

Pelo log do portainer vi que não está gerando a fila.
Criei a fila manualmente e ela populou corretamenta.

### What did you expect?

Crie a fila para cada evento e instancia no SQS

### What did you observe instead of what you expected?

Não gerava fila e só gerou manualmente.

### Screenshots/Videos

Fila criada manualmente
![image](https://github.com/user-attachments/assets/227ec2b6-7625-4471-8fe6-181398c1fd04)
---
Após criar a fila da certo
<img width="269" alt="image" src="https://github.com/user-attachments/assets/0e4dcc73-5b45-4ea9-be6c-42f1671780f1">
---
Ele não encontrando fila, que ele deveria ter criado
<img width="1074" alt="image" src="https://github.com/user-attachments/assets/ef75b411-29de-4cfb-a0d7-fdc437751cf7">

### Which version of the API are you using?

V 2.1.0

### What is your environment?

Docker

### Other environment specifications

2GB Ram 4 CPUv

### If applicable, paste the log output

{
  local: 'p.sendData-SQS',
  message: 'The specified queue does not exist.',
  hostName: undefined,
  code: undefined,
  stack: 'QueueDoesNotExist: The specified queue does not exist.\n' +
    '    at de_QueueDoesNotExistRes (/evolution/node_modules/@aws-sdk/client-sqs/dist-cjs/index.js:1475:21)\n' +
    '    at de_CommandError (/evolution/node_modules/@aws-sdk/client-sqs/dist-cjs/index.js:1201:19)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async /evolution/node_modules/@smithy/middleware-serde/dist-cjs/index.js:35:20\n' +
    '    at async /evolution/node_modules/@smithy/core/dist-cjs/index.js:165:18\n' +
    '    at async /evolution/node_modules/@smithy/middleware-retry/dist-cjs/index.js:320:38\n' +
    '    at async /evolution/node_modules/@aws-sdk/middleware-sdk-sqs/dist-cjs/index.js:131:16\n' +
    '    at async /evolution/node_modules/@aws-sdk/middleware-logger/dist-cjs/index.js:34:22',
  name: 'QueueDoesNotExist',
  url: '01-instance-dotcoding_presence_update.fifo',
  server_url: '<<ocultado>>
}

**Comment by dpaes** [comment]
Ainda persiste o problema? Caso seja um sim, tente usar a versão 2.1.2 do evolution e valide se persiste esse problema, caso ainda assim persista, nos informe nos comentarios.

**Comment by paulofellix** [comment]
Fiz testes usando a versão 2.1.2 e também usando a versão 2.2.0, o erro persiste, ao setar o sqs ele parece não executar a funcão de criar a fila no sqs

![image](https://github.com/user-attachments/assets/58d7f777-8615-489e-890b-5136c1ed0fa1)

**Comment by fernandoralha** [comment]
> [@dpaes](https://github.com/dpaes) Fiz testes usando a versão 2.1.2 e também usando a versão 2.2.0, o erro persiste, ao setar o sqs ele parece não executar a funcão de criar a fila no sqs
> 
> ![image](https://github.com/user-attachments/assets/58d7f777-8615-489e-890b-5136c1ed0fa1)
> 
> Aparentemente a função que cria as filas é essa `initQueues` no arquivo `src/api/integrations/event/sqs/sqs.controller.ts`, porém essa função é chamada em nenhum outro lugar do código
> 
> ![image](https://github.com/user-attachments/assets/6be81194-093e-4658-a896-a5698a26b408)

O problema foi resolvido na versao 2.2.2?

**Comment by fernandoralha** [comment]
Opa, verifiquei que não foi resolvido. Enviei uma PR para os mantenedores avaliarem e subirem para a branch principal.
