### ISSUE TITLE
Typebot dando erro localhost

### ISSUE THREAD

**Issue by DeusYe** [EvolutionAPI/evolution-api#884]
Não consigo integrar via localhost a evolution 1.8.2 com o typebot.

abaixo a mensagem do erro:

[Evolution API]    v1.8.2  1377927   -  Thu Sep 12 2024 11:25:47     ERROR   [TypebotService]  [object]
TypeError: Cannot read properties of undefined (reading 'messages')
    at TypebotService.<anonymous> (/home/infoprime/evolution-api/evolution-api/dist/src/api/integrations/typebot/services/typebot.service.js:669:72)
    at Generator.next (<anonymous>)
    at fulfilled (/home/infoprime/evolution-api/evolution-api/dist/src/api/integrations/typebot/services/typebot.service.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by dpaes** [comment]
o evo e o typebot estão funcionando isoladamente um do outro? Se sim, vc na hora de fazer a integração, precisa entender sobre como definir o caminho correto para funcionar em localhost, a maioria usa tudo em vps, então é resolvido usando apontamento de dominio e o proxy reverso cuida de direcionar corretamente. dai nas variaveis de ambiente tem o typebot front e o typebot back pra poder ao integrar ficar facil para as aplicações se comunicarem, no localhost vc teria que ter mais conhecimento p fazer funcionar, a maioria dos tutoriais são usando VPS mesmo. Se não conseguir sugiro pegar uma vps para testes, tem varias com trial bem generoso, seria uma outra opção.

**Comment by DeusYe** [comment]
eu rodo o chatwoot tambem em localhost, tudo em um servidor ubuntu proprio meu, e funciona normalmente, so typebot que não esta funcionando...

**Comment by DeusYe** [comment]
![Captura de tela 2024-09-12 122928](https://github.com/user-attachments/assets/6b4726c3-c23c-489a-b05f-79aa270880a7)

**Comment by dpaes** [comment]
veja como vc definiu o backend e o front end do typebot, talvez o problema esteja ai
