### ISSUE TITLE
Erro ao enviar arquivos

### ISSUE THREAD

**Issue by keven-cerrado** [EvolutionAPI/evolution-api#891]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

![Captura de tela 2024-09-16 113304](https://github.com/user-attachments/assets/d5743682-d916-4597-b771-1030c7364d86)

Sempre que estou tentando enviar arquivos, da esse mesmo erro!
Eu tenho apenas 1 instancia na EVO

### What did you expect?

Enviar o arquivo

### What did you observe instead of what you expected?

(node:170) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 end listeners added to [Readable]. MaxListeners is 10. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
(node:170) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [Readable]. MaxListeners is 10. Use emitter.setMaxListeners() to increase limit
(node:170) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [Readable]. MaxListeners is 10. Use emitter.setMaxListeners() to increase limit
[Evolution API]  [AtendimentoTI]  v2.1.0  170   -  Mon Sep 16 2024 11:38:42     ERROR   [ChannelStartupService]  [string]  line 2378
[Evolution API]  [AtendimentoTI]  v2.1.0  170   -  Mon Sep 16 2024 11:38:42     ERROR   [ChannelStartupService]  [object]
Error: Media upload failed on all hosts
    at Object.upload (/evolution/node_modules/baileys/lib/Utils/messages-media.js:577:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /evolution/node_modules/baileys/lib/Utils/messages.js:122:28
    at async Promise.all (index 0)
    at async prepareWAMessageMedia (/evolution/node_modules/baileys/lib/Utils/messages.js:120:40)
    at async Ms.prepareMediaMessage (/evolution/dist/main.js:203:13692)
    at async Ms.mediaMessage (/evolution/dist/main.js:203:15882)
    at async he.sendAttachment (/evolution/dist/main.js:76:16196)
    at async he.receiveWebhook (/evolution/dist/main.js:78:232)
    at async ai.dataValidate (/evolution/dist/main.js:214:101852) {
  data: null,
  isBoom: true,
  isServer: true,
  output: {
    statusCode: 500,
    payload: {
      statusCode: 500,
      error: 'Internal Server Error',
      message: 'An internal server error occurred'
    },
    headers: {}
  }
}

[Evolution API]    v2.1.0  170   -  Mon Sep 16 2024 11:38:42     ERROR   [ChatwootService]  [object]
{
  status: 500,
  error: 'Internal Server Error',
  message: [ 'Error: Media upload failed on all hosts' ]
}

### Screenshots/Videos

![image](https://github.com/user-attachments/assets/c6aeecef-4d17-407b-a822-a57c1986d7d1)

### Which version of the API are you using?

2.1.0

### What is your environment?

Docker

### Other environment specifications

![image](https://github.com/user-attachments/assets/af08dfa5-4c6c-441f-83c1-332e2bc8530b)

**Comment by liluyoud** [comment]
Eu tive o mesmo erro e não consegui tirar. Pelo que vi não está acontecendo com todos. Mas para resolver meu caso, acabei voltando para a versão 2.0.10 que está conseguindo enviar pelo menos

**Comment by andersoncobuci** [comment]
> Eu tive o mesmo erro e não consegui tirar. Pelo que vi não está acontecendo com todos. Mas para resolver meu caso, acabei voltando para a versão 2.0.10 que está conseguindo enviar pelo menos

Aqui mesma coisa, revirei tudo e não achei solução, apenas fazendo o downgrade

**Comment by dpaes** [comment]
Chegaram a testar em uma versão mais recente como 2.1.2 ou 2.2.0?

**Comment by liluyoud** [comment]
Sim, estou usando a 2.2 e agora está td certo. Vlw

**Comment by pedroepif** [comment]
Versão 2.1.2 segue com o mesmo problema, alguma possível solução?

**Comment by dpaes** [comment]
testou na 2.2.1 @pedroepif ?

**Comment by joao-baza** [comment]
Mesmo erro aqui, em >2.2

**Comment by felipesoares-tech** [comment]
@joao-baza , estou com o mesmo problema, vc conseguiu alguma solução? ja fiz downgrade p/ outras versões mas dá o mesmo erro.

**Comment by gabrielxp42** [comment]
Versão: 2.2.0

E segue o mesmo erro, o mais doido é que
ontem do nada ele funcionou normal, e hoje parou novamente sem eu ter alterado nada.

**Comment by joao-baza** [comment]
O problema aleatoriamente vai e vem, em diversas versões, com e sem proxy, com todos os media types que testei. Pessoalmente, migrei pra fora da Evo em tudo que pude.
