### ISSUE TITLE
User(mobile) reply message with image or audio

### ISSUE THREAD

**Issue by drecchia** [EvolutionAPI/evolution-api#921]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

When customer using whatsapp reply message with image or audio, evolution-api server presents en error an messages are not integrated in chatwoot.

### What did you expect?

Normal integration with same behaviour as text reply

### What did you observe instead of what you expected?

Evolution-api throws error on console, no message integration occurs.

### Screenshots/Videos

![image](https://github.com/user-attachments/assets/e91e988b-8444-4ebc-a1cb-066e7d8fd2f1)

### Which version of the API are you using?

v2.1.1

### What is your environment?

Docker

### If applicable, paste the log output

Throw error:

```
 [Evolution API]  212 - Thu Sep 26 2024 08:38:49   ERROR  [ChatwootService] [object] TypeError: source.on is not a function
     at DelayedStream.create (/evolution/node_modules/delayed-stream/lib/delayed_stream.js:33:10)
     at CombinedStream.append (/evolution/node_modules/combined-stream/lib/combined_stream.js:45:37)
     at FormData.append (/evolution/node_modules/form-data/lib/form_data.js:75:3)
     at he.sendData (/evolution/dist/main.js:76:14238)
     at async he.eventWhatsapp (/evolution/dist/main.js:119:138)
     at async messages.upsert (/evolution/dist/main.js:215:19481)
 [Evolution API] [danilo] 212 - Thu Sep 26 2024 08:38:49   LOG  [ChannelStartupService] [object] {
   key: {
     remoteJid: '5519981133671@s.whatsapp.net',
     fromMe: true,
     id: 'F899108A3E48E9A8803BE2A0E45B9490',
     participant: undefined
   },
   pushName: 'Danilo',
   message: {
     imageMessage: ImageMessage {
       interactiveAnnotations: [],
       scanLengths: [Array],
       annotations: [],
       url: 'https://mmg.whatsapp.net/o1/v/t62.7118-24/f1/m231/up-oil-image-7c6dd3b6-1325-466c-bf5c-082cc8a7ee47?ccb=9-4&oh=01_Q5AaIKQ3fbgy3qPyax3tqfm3lsfyuUpvmyRsPR9kpVJuCP1G&oe=671CD284&_nc_sid=e6ed6c&mms3=true',
       mimetype: 'image/jpeg',
       fileSha256: [Uint8Array],
       fileLength: [Long],
       height: 719,
       width: 1600,
       mediaKey: [Uint8Array],
       fileEncSha256: [Uint8Array],
       directPath: '/o1/v/t62.7118-24/f1/m231/up-oil-image-7c6dd3b6-1325-466c-bf5c-082cc8a7ee47?ccb=9-4&oh=01_Q5AaIKQ3fbgy3qPyax3tqfm3lsfyuUpvmyRsPR9kpVJuCP1G&oe=671CD284&_nc_sid=e6ed6c',
       mediaKeyTimestamp: [Long],
       jpegThumbnail: [Uint8Array],
       contextInfo: [ContextInfo],
       scansSidecar: [Uint8Array],
       midQualityFileSha256: [Uint8Array]
     },
     base64: '/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAYGBgYHBgcICAcKCwoLCg8ODAwODxYQERAREBYiFRkVFRkVIh4kHhweJB42KiYmKjY+NDI0PkxERExfWl98fKcBBgYGBgcGBwgIBwoLCgsKDw4MDA4PFhAREBEQFiIVGRUVGRUiHiQeHB4kHjYqJiYqNj40MjQ+TERETF9aX3x8p//CABEIAs8GQAMBIgACEQEDEQH/xAAwAAADAQEBAQAAAAAAAAAAAAAAAQIDBAUGAQEBAQEBAAAAAAAAAAAAAAAAAQIDBP/aAAwDAQACEAMQAAAC9oDeAAAAGAAAAAUAABBNBktiue9Qx0vONDnK6DCTqedRRIPO8T51NTW3veD76aAayJoAAAAAAAABpgAAAAAAAAAAAAAAAAAAAAAAAAAAAAwIAAAABQBAAAAAAAAAAA'... 245412 more characters
   },
   contextInfo: ContextInfo {
     mentionedJid: [],
     groupMentions: [],
     stanzaId: '0A4AE77AE63930CA12',
     participant: '5519981133671@s.whatsapp.net',
     quotedMessage: Message { conversation: 'hoho' }
   },
   messageType: 'imageMessage',
   messageTimestamp: 1727350729,
   instanceId: '8c2c5dc4-dd92-4b43-80b4-299ca1c205dc',
   source: 'android'
 }

```

**Comment by xiribitarp** [comment]
Fiz um teste na versão 2.1.0 e no Chatwoot não aparece a mensagem que estou respondendo.
Realizei o rollback para 2.1.0 pois é melhor receber todas as mensagens no Chatwoot do que não receber as mensagens que são respondidas com audio ou imagem.

**Comment by dpaes** [comment]
ja tentou atualizar pra 2.1.2? pra mim ela funciona perfeitamente
