### ISSUE TITLE
EVO 2.1.1 - Error communicating via webhook sending audio or image

### ISSUE THREAD

**Issue by wilsonfe** [EvolutionAPI/evolution-api#942]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

I found a bug in Evo version 2.1.1. When communicating via webhook by sending audio or image, the base64 field is not being sent. This same error does not occur in version 2.1.0.

### What did you expect?

That the base64 field was sent with the audio or image data.

### What did you observe instead of what you expected?

That the base64 field was sent with the audio or image data.

### Screenshots/Videos

![download (6)](https://github.com/user-attachments/assets/61edd806-e641-463e-9bf6-dd485f1bb70e)
![download (5)](https://github.com/user-attachments/assets/2ffe70ca-cc7e-4bbc-ae06-a7274f40900d)
![download (4)](https://github.com/user-attachments/assets/cc2e0216-32e4-4e3a-b81c-5875175dccd3)

### Which version of the API are you using?

2.1.1

### What is your environment?

Linux

### If applicable, paste the log output

erro do áudio

Stack trace

NodeOperationError: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received null at Object.execute (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Files/ConvertToFile/actions/toBinary.operation.js:142:19) at processTicksAndRejections (node:internal/process/task_queues:95:5) at Object.execute (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Files/ConvertToFile/ConvertToFile.node.js:135:26) at Workflow.runNode (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/Workflow.js:722:19) at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:670:51 at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:1100:20

### Additional Notes

erro da imagem

Stack trace

NodeOperationError: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received null at Object.execute (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Files/ConvertToFile/actions/toBinary.operation.js:142:19) at processTicksAndRejections (node:internal/process/task_queues:95:5) at Object.execute (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Files/ConvertToFile/ConvertToFile.node.js:135:26) at Workflow.runNode (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/Workflow.js:722:19) at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:670:51 at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:1100:20

**Comment by inbtec** [comment]
I'm having problems with this too

**Comment by ip2cloud** [comment]
I'm having problems with this too

**Comment by ip2cloud** [comment]
fixed in version  release-0.9.2 can close

**Comment by dpaes** [comment]
@wilsonfe can confirm if u still with this problem in another version more recent of evolution-api? like 2.1.2 or 2.2.0?

**Comment by wilsonfe** [comment]
> @wilsonfe can confirm if u still with this problem in another version more recent of evolution-api? like 2.1.2 or 2.2.0?

I'm using 2.2.0 and haven't had the problem.

**Comment by bbrak** [comment]
Working with 2.2.0 here and facing he exact same issue

**Comment by SebaGPDev** [comment]
> Working with 2.2.0 here and facing he exact same issue

Also me

**Comment by dpaes** [comment]
just for an tip, depending of the size in the file (audio or video), the base64 caracters have an limit to send in a request, so if the file its too large, cant be sended in base64. one another way its use minIO or another storage, to when sending an midia, the size of the file can be bigger.

**Comment by diegoirs23** [comment]
Estou com esse problema, não consigo enviar imagens e nem audio usando a API OFICIAL. Estou usando a 2.2

**Comment by dpaes** [comment]
o problema mencionado @diegoirs23 pelo seu pode ser diferente do caso do que criou a issue pelo fato dele estar usando o canal baileys e vc estar usando api oficial com o evolution. Logo no seu caso pode ser bug mesmo @diegoirs23. Por isso abra uma issue separada que ja estamos corrigindo para a proxima versão que vai lançar final desse mês com varias correções.

**Comment by hrxm** [comment]
Hi, I'm having this same issue with v2.2.3. Changed to v2.2.0 and working.

![Image](https://github.com/user-attachments/assets/22303b2c-ba18-4c42-81fc-13ce15c8001b)

**Comment by spirit14** [comment]
in Evolution Api Dashboard juste make an restart and refresh that will fix the problem.

<img width="595" height="358" alt="Image" src="https://github.com/user-attachments/assets/14a7e651-c1a7-41f2-a80c-951c964a2c5a" />
