### ISSUE TITLE
[BUG] password authentication failed for user "postgres" - v2.2.0-homolog

### ISSUE THREAD

**Issue by tiagocaus** [EvolutionAPI/evolution-api#998]
Ao migrar da V2.1.2 para v2.2.0-homolog apareceu esse erro duas vezes em tela:

```
[Evolution API]    v2.2.0  169   -  Wed Oct 23 2024 05:42:17     ERROR   [unhandledRejection]  [object]   
error: password authentication failed for user "postgres"
    at /evolution/node_modules/pg-pool/index.js:45:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Me.syncLostMessages (/evolution/dist/main.js:142:35) {
  length: 104,
  severity: 'FATAL',
  code: '28P01',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'auth.c',
  line: '330',
  routine: 'auth_failed'
}
```

**Comment by AlejoTorres2001** [comment]
Im facing the same issue here

**Comment by dsursulino** [comment]
managed to solve it, I have the same problem?
